"""Core experimental models for Veyra."""

from . import _legacy as _legacy_aliases

_legacy_aliases.install(__name__)

from .kernel.axiom_kernel import AxiomKernelReport, AxiomWitness, KernelAxiom, LayerAxiomUse, axiom_kernel_checklist, axiom_kernel_report, axiom_witness_rows, layer_axiom_dependencies, unified_axiom_kernel
from .formal.bridge import FormalProofCertificate, FormalProofStep, LeanCheckResult, check_formal_proof, check_lean_echo_export, echo_reflexive_certificate, echo_reflexive_proof_steps, formal_bridge_checklist, formal_bridge_summary, lean_echo_export_path
from .kernel.semantic_kernel import DerivationReceipt, ReceiptCheck, SemanticResult, axiom_closure, evaluate_native, observer_adapter, replay_receipts, verify_receipts
from .kernel.layer_derivations import LayerDerivation, LayerDerivationReport, layer_derivation_report, layer_derivations
from .formal.native_bridge import NativeFormalBridgeReport, intrinsic_arithmetic_lean_status, native_formal_bridge_report
from .formal.completion import FormalExportCompletionRow, binomial_symmetry_completion_row, completed_formal_export_rows, cyclic_period_completion_row, formal_export_completion_checklist, formal_export_completion_summary, lean_algebra_export_path, lean_combinatorics_export_path, lean_probability_export_path, lean_statistics_export_path, line_shell_intersection_completion_row, linear_equation_completion_row, lean_cyclic_period_export_path, lean_pythagorean_export_path, mean_balance_completion_row, plane_relabel_composition_completion_row, polynomial_evaluation_completion_row, polynomial_identity_completion_row, probability_complement_completion_row, probability_independence_completion_row, probability_union_completion_row, pythagorean_separation_completion_row, sas_triangle_completion_row, sss_triangle_completion_row, variance_shift_completion_row
from .formal.remaining_completion import AREA_ADDITIVITY_ID, AREA_ADDITIVITY_SYMBOL, CHORD_SYMMETRY_ID, CHORD_SYMMETRY_SYMBOL, DRIFT_STABILITY_ID, DRIFT_STABILITY_SYMBOL, SAMPLED_CONTINUITY_ID, SAMPLED_CONTINUITY_SYMBOL, area_additivity_completion_row, chord_symmetry_completion_row, drift_stability_completion_row, sampled_continuity_completion_row
from .formal.prep import FormalExportPrepRow, checked_bridge_rows, formal_export_prep_checklist, formal_export_prep_rows, formal_export_prep_summary, stable_card_export_prep_rows
from .registry.theorem_language import ProofObligation, TheoremCheck, TheoremEnvironment, TheoremProposition, TheoremQuantifier, TheoremStatement, check_theorem_statement, default_theorem_environments, parse_theorem_statement, theorem_language_checklist, theorem_obligation_rows
from .shadows.algebra_analysis_cards import PolynomialIdentityEvidence, area_additivity_card, continuity_card, drift_stability_card, linear_equation_card, polynomial_evaluation_card, polynomial_identity_card
from .shadows.benchmark_derivations import BenchmarkDerivationRow, benchmark_derivation_checklist, benchmark_derivation_rows, benchmark_derivation_summary, derive_benchmark_verdict
from .shadows.balance import BalanceMode, balance_from_int
from .shadows.calculus_depth import IntegralCoherence, LocalLinearization, antiderivative_polynomial, calculus_depth_checklist, chain_rule_card, compose_polynomials, integral_coherence, integral_coherence_card, linearization_error, local_linearization, polynomial_power, product_rule_card, scale_polynomial
from .shadows.classical_benchmarks import ClassicalBenchmarkCard, classical_benchmark_cards, classical_benchmark_checklist, classical_benchmark_summary
from .formal.deduction_chain import DeductionLink, DeductionProofRow, deduction_chain_checklist, deduction_chain_summary, deduction_links, deduction_proof_rows
from .shadows.category_like import InvariantRow, MorphismClosureRow, UniversalShadowRow, VeyraMorphism, VeyraObject, category_closure_rows, category_invariant_rows, category_like_checklist, category_like_examples, category_like_morphisms, category_like_summary, category_universal_shadow_rows, compose_morphisms, morphism_closure_row, morphism_graph, ratio_object
from .geometry.topology_echo import DeformationEchoRow, EchoShape, TopologyObstructionCard, deformation_echo_row, deform_shape, echo_shape, invariant_value, subdivide_corridor, topology_echo_checklist, topology_echo_shapes, topology_echo_summary, topology_invariant_rows, topology_obstruction_cards
from .shadows.change import AreaCertificate, ContinuityCertificate, DriftQuotient, difference_quotient, riemann_area, sampled_continuity, symmetric_difference_quotient
from .shadows.completion import CompletionInterval, LimitCertificate, square_refinement, tail_limit_certificate
from .shadows.convergence_algebra import CauchyTailCertificate, MajorantBound, NestedIntervalCertificate, RadiusGuard, cauchy_tail_card, cauchy_tail_certificate, convergence_algebra_checklist, majorant_bound, majorant_bound_card, nested_interval_card, nested_interval_certificate, radius_guard, radius_guard_card, ratio_abs_distance
from .numbers.compression_algebra import CompressionTree, CostComparisonRow, EditResonanceProfile, PolynomialFactorHit, compare_cost_strategies, compression_algebra_checklist, divide_by_linear_root, edit_distance, edit_resonance_profile, hierarchical_compression_tree, polynomial_factor_search
from .numbers.cyclic_probability_stats import CyclicPhase, FiniteDistribution, SampleEcho, WeightedOutcome, chord_symmetry_card, cyclic_chord_echo, expectation, mean_balance_card, phase_period_card, probability_complement_card, probability_of, sample_mean, sample_variance
from .registry.curriculum_map import CurriculumEdge, CurriculumGap, CurriculumNode, CurriculumSummary, curriculum_edges, curriculum_summary, missing_curriculum_concepts, sage_export_rows, school_curriculum_nodes
from .registry.curriculum_topics import SchoolTopicCoverage, school_topic_coverage_rows, school_topic_gap_rows
from .registry.depth_packs import SageExportRow, binomial_symmetry_card, choose_echo, curriculum_sage_export_rows, factorial_echo, independence_card, probability_union_card, theorem_sage_export_rows, variance_shift_card
from .shadows.equation import LinearEquation, LinearForm, solve_linear
from .kernel.essence import VeyraCoreLayer, VeyraEssenceAxiom, VeyraEssenceReport, core_layers, essence_axioms, essence_checklist, essence_report
from .geometry import EventPoint, TremorCorridor, corridor_contains, corridor_interpolate, corridor_midpoint, squared_separation, triangle_area, turn_2d
from .geometry.relations import CongruenceCertificate, PlaneRelabel, ShellCertificate, TriangleSignature, circle_shell, corridor_congruence, parallel_corridors_2d, quarter_turn_relabel, relabel_event, scale_relabel, translation_relabel, triangle_congruence
from .geometry.theorems import IntersectionCard, TheoremCard, compose_relabels, identity_relabel, line_shell_intersections, pythagorean_card, sas_card, sss_card
from .geometry.visual_regression import GeometryVisualSnapshot, geometry_visual_regression_checklist, geometry_visual_regression_summary, geometry_visual_scene_rows, geometry_visual_snapshots, render_visual_scene, visual_digest
from .language import SchoolTranslation, VeyraCheck, VeyraExpr, VeyraInterpretation, VeyraKind, core_language_checklist, expr_kind, infer_veyra, interpret_veyra, normal_text, normalize_veyra, parse_veyra, school_translation_table
from .language.span_coverage import VeyraSpanCoverageReport, VeyraSpanDiagnosticCase, VeyraSpanDiagnosticResult, missed_span_diagnostic_rules, run_span_diagnostic_case, run_span_diagnostic_coverage, span_diagnostic_cases, span_diagnostic_coverage_checklist, span_diagnostic_coverage_report
from .language.span import ParseDiagnostic, SourceSpan, SpannedExpr, SpannedParseResult, VeyraToken, diagnostic_excerpt, lex_veyra, parse_veyra_spanned, span_language_checklist, span_to_plain, spanned_normal_text
from .shadows.linear_algebra import MatrixTransformer, VectorMode, determinant_2x2, determinant_product_card, dot_row, eigen_candidate_card, linear_algebra_seed_checklist, matrix_from_ints, matrix_multiply, matrix_vector_apply, trace_2x2, vector_from_ints, zero_vector
from .language.proof import VeyraProofStep, VeyraProofSummary, VeyraProofTrace, proof_language_checklist, proof_summary, trace_veyra_proof
from .shadows.likelihood_geometry import DomainResidualCertificate, LikelihoodPeakCard, LikelihoodPoint, LikelihoodSegment, domain_residual_certificate, finite_likelihood_segments, likelihood_geometry_checklist, likelihood_geometry_summary, likelihood_grid, likelihood_peak_card, likelihood_point, residual_family_certificates
from .registry.proof_discipline import PrimitiveModelNote, RuleCoverageCell, SemanticDomainRow, StableExportRow, primitive_model_notes, proof_discipline_checklist, proof_discipline_summary, proof_rule_coverage, proof_rule_coverage_summary, semantic_domain_coverage, stable_formal_export_rows
from .surprise import VeyraSurpriseWitness, best_surprise_for_mode, find_surprise_witnesses, surface_exact_saving, surprise_checklist
from .surprise.kwise import KWiseBaselineSignature, KWiseHiddenCorrelationRow, bit_words, global_parity_counts, kwise_baseline_signature, kwise_hidden_correlation_checklist, kwise_hidden_correlation_summary, kwise_parity_hidden_correlation_row
from .surprise.debruijn import DeBruijnBaselineSignature, DeBruijnTrailRow, cyclic_window_count_signature, cyclic_windows, debruijn_baseline_signature, debruijn_hidden_checklist, debruijn_hidden_summary, debruijn_trail_adjacencies, debruijn_trail_hidden_row
from .surprise.separation import BaselineAuditRow, ClassicalBlindSignature, ExpandedClassicalSignature, SurpriseSeparationRow, canonical_surprise_separation_row, classical_baseline_signature, expanded_baseline_audit_rows, expanded_classical_signature, surprise_separation_checklist, surprise_separation_rows, surprise_separation_summary
from .surprise.search import HiddenCorrelationRow, PairwiseBaselineSignature, SurpriseSearchRow, WordSurpriseScore, expanded_baseline_search_row, hidden_correlation_rows, pairwise_baseline_signature, surprise_search_checklist, surprise_search_summary, xor_hidden_correlation_row
from .shadows.statistics_inference import DistributionFamily, IntervalEstimate, bernoulli_family, hypothesis_mean_card, interval_contains_shadow, mean_interval, sample_echo_from_ints, standard_error_shadow, statistics_inference_checklist
from .shadows.statistics_concentration import BernoulliLikelihoodRow, ConcentrationBound, DecisionErrorRow, bernoulli_likelihood_row, chebyshev_mean_bound, concentration_bound_card, decision_error_row, hoeffding_exponent_guard, likelihood_ratio_card, statistics_concentration_checklist
from .language.coverage import VeyraCoverageCell, VeyraCoverageReport, coverage_language_checklist, language_coverage_matrix, language_coverage_report, missed_language_coverage_rules
from .language.fuzz import VeyraGeneratedMutationReport, VeyraMutationCase, VeyraMutationReport, VeyraMutationResult, VeyraPropertyFuzzReport, generated_language_mutation_cases, generated_language_mutation_report, generated_mutation_language_checklist, language_mutation_cases, language_mutation_report, mutation_language_checklist, property_fuzz_language_checklist, property_language_fuzz_report, property_language_mutation_cases, run_generated_language_mutations, run_language_mutation_case, run_language_mutations, run_property_language_fuzz, shrink_language_mutation_case
from .native_runtime import Breath, NativeEcho, NativeObstruction, NativeObserver, NativeShadowRow, Nod, Rez, Tact, echo_native, mode, native_observers, native_runtime_checklist, native_runtime_report, native_shadow_rows, nod, observe_native, rez, shadow_from_native, stitch, tact, breath
from .intrinsic_arithmetic import DivisionStep, EscapeWitness, ProductPlusOneObstructionProof, StructuralDivisionProof, intrinsic_arithmetic_summary, mode_power, one, one_mode, power, product_plus_one_escape, product_plus_one_obstruction, structural_divide, structural_division, successor, weave, zero, zero_mode
from .observer.synthesis import CandidateEvaluation, FittedObserver, HoldoutReport, NamedBaseline, ObserverCase, ObserverCaseEvidence, ObserverGrammar, ObserverPrimitive, ObserverResponse, ObserverSynthesisResult, ObserverTerm, StrictObserverClassCertificate, SynthesisConfig, SynthesisObstruction, canonical_term, enumerate_observer_terms, evaluate_observer, fit_observer, observer_fingerprint, observer_synthesis_summary, observer_term_cost, observer_term_text, parity_baselines, parity_holdout_cases, parity_observer_grammar, parity_observer_synthesis, parity_table, parity_train_cases, proper_marginal_signature, score_observer, strict_observer_class_certificate, synthesize_observer, validate_observer, xor_rows
from .numbers.native_number import CycleDivisibilityRow, CycleEcho, PrimeObstructionRow, PrimitiveCountRow, PrimitivePhaseProfile, RankFactorRow, SpectrumCompressionRow, compare_spectrum_compression, cycle_divisibility_row, cycle_echo, cycle_equivalent, cyclic_weave_echo, native_number_checklist, native_number_theory_checklist, primitive_count_table, primitive_phase_profile, prime_obstruction_rows, rank_factor_comparison
from .geometry.native_derivations import NativeRightCornerRow, native_axis_breath, native_geometry_derivation_rows, native_geometry_derivation_summary, native_right_corner_row
from .numbers.native_number_theorems import EuclidEscapeRow, NativeEuclidModeRow, NativeFermatPhaseRow, euclid_escape_row, lean_euclid_bridge_ready, native_euclid_mode_row, native_euclid_mode_rows, native_euclid_rows, native_fermat_obstruction_rows, native_fermat_phase_row, native_fermat_phase_rows, native_number_theorem_gaps, native_number_theorem_summary
from .registry.theorem_registry import RegistryCheck, RegistrySummary, TheoremSpec, algebra_analysis_theorem_specs, all_theorem_specs, check_card, dependency_edges, depth_pack_theorem_specs, geometry_theorem_specs, registry_summary
from .shadows.trigonometry_identities import TrigIdentityVector, compose_phases, conjugate_phase, double_angle_identity_card, inverse_phase_identity_card, pythagorean_identity_card, sum_angle_identity_card, trig_vector_from_ints, trigonometry_identity_checklist, unit_identity_gap
from .numbers.phase_equations import PhaseCoordinateRow, PhasePairRow, default_phase_basis, inverse_phase_obstruction_card, phase_coordinate_row, phase_equation_checklist, phase_equation_normal_form_card, phase_pair_row
from .quantum.error_obstructions import QuantumErrorObstructionRow, branch_distinguishability_row, interference_loss_row, leakage_row, nonunitarity_row, phase_break_row, quantum_error_obstruction_checklist, quantum_error_obstruction_rows, quantum_error_obstruction_summary, syndrome_ambiguity_row
from .quantum.gate_identities import GateIdentityBaselineRow, GateIdentityRow, cnot_conjugation_rows, gate_equal, gate_identity_baseline_rows, gate_identity_rows, gate_phase_equal, gate_word, q_gate_i2, q_gate_s, q_gate_z, quantum_gate_identity_checklist, quantum_gate_identity_summary, scale_gate
from .quantum.baselines import QuantumBaselineRow, quantum_baseline_checklist, quantum_baseline_rows, quantum_baseline_summary
from .quantum.circuit_compression import CircuitCompressionRow, circuit_compression_checklist, circuit_compression_rows, circuit_compression_summary
from .quantum.qec_echo import QECAmbiguityRow, QECBranchRow, QECObserverFamilyRow, QECSplitEchoRow, branch_shadow, qec_ambiguity_rows, qec_branch, qec_branch_rows, qec_echo, qec_observer_family_rows, qec_split_echo_rows, quantum_qec_echo_checklist, quantum_qec_echo_summary
from .quantum.qft_period import QFTOffsetEchoRow, QFTPeriodObstructionRow, QFTPeriodRow, expected_period_frequencies, observed_frequencies, phase_orbit, qft4_gate, qft_offset_echo_row, qft_period_obstruction_row, qft_period_row, qft_period_rows, qft_period_state, qft_shadow, quantum_qft_period_checklist, quantum_qft_period_summary
from .quantum.topology import QBraidOrderRow, QTopoEchoRow, QTopoLogicalRow, QTopoObstructionRow, VTopoQubit, braid_shadow, loop_action, qbraid_order_rows, qtopo_echo, qtopo_echo_rows, qtopo_logical_rows, qtopo_obstruction_rows, quantum_topology_checklist, quantum_topology_summary, topo_broken_shape, topo_deformed_shape, topo_shape, topo_signature, vtopo_qubit
from .quantum.stabilizer import LogicalObstructionRow, PauliRow, StabilizerEchoRow, SyndromeRow, apply_x, correction_for_syndrome, logical_observer, logical_obstruction_rows, pauli_x_rows, quantum_stabilizer_checklist, quantum_stabilizer_summary, stabilizer_echo_rows, syndrome, syndrome_rows
from .quantum.veyra import QAmp, QGate, QMode, QuantumTheoremCard, Rad2, bell_state, compose_gate, is_product_factorable_2q, observer_distribution, q_basis_state, q_gate_cnot, q_gate_h, q_gate_i, q_gate_x, qecho, quantum_theorem_cards, quantum_veyra_checklist, quantum_veyra_summary, tensor_gate
from .shadows.transcendental_limit import FormalSeriesShadow, LimitEnvelope, alternating_log1p_envelope, alternating_tail_bound_card, exp_derivative_card, exp_series, factorial_int, geometric_alt_series, log1p_derivative_card, log1p_series, series_value, transcendental_limit_checklist
from .numbers.modes import Mode, natural_mode, natural_shadow, weave_by_length
from .shadows.order import RatioInterval, compare_balances, compare_ratios
from .shadows.polynomial import Polynomial
from .shadows.power import LiftResult, discrete_log_shadow, nth_root_shadow, ratio_power
from .shadows.ratio import RatioMode, ratio_from_ints
from .shadows.real_analysis_structure import FiniteModulusCertificate, RefinementStabilityCertificate, area_refinement_certificate, derivative_refinement_certificate, finite_modulus_certificate, identity_rule, jump_obstruction_card, jump_rule, real_analysis_structure_checklist, square_rule
from .shadows.weighted_measure import AdditivityRow, CoverageRow, PushForwardRow, WeightedEchoAtom, WeightedEchoMeasure, coverage_row, finite_additivity_row, mass_of, overlap_gap_card, pushforward_by_tact, weighted_echo_measure, weighted_measure_checklist
from .shadows.science_certificates import ConservationRow, DiffusionRow, FlowBalanceRow, FlowEdge, anti_diffusion_obstruction_card, finite_conservation_row, finite_diffusion_row, finite_flow_balance_row, ratio_total, ratio_variation, science_certificate_checklist
from .shadows.model_diagnostics import ModelComparisonRow, ModelFitReport, ModelObservation, ResidualRow, absolute_ratio, anomaly_obstruction_card, baseline_model_observations, canonical_model_observations, compare_model_reports, model_diagnostics_checklist, model_fit_report, residual_row
from .shadows.scale_memory_log import CyclicDepthCertificate, ScaleMemoryLogCertificate, TransitionDepthRow, finite_field_log_fixture, recover_cyclic_depth, recover_transition_depth, residual_ratio, scale_memory_log_checklist, scale_memory_obstruction_card, transition_depth_rows
from .shadows.transformer import ModeTransformer, apply_transformer, compose_transformers
from .surprise.veyra_magic import MagicAuditRow, VEYRA_MAGIC_THESIS, magic_audit_checklist, magic_audit_rows, magic_audit_summary
from .observer.descent import BestLowerApproximation, CREST_BRAID_SCHEMA, CrestBraid, CrestTact, FiniteObserver, FiniteObserverDoctrine, FiniteTransition, OBSERVER_BALANCE_SCHEMA, OBSERVER_DESCENT_SCHEMA, OBSERVER_DOCTRINE_SCHEMA, ObserverDescent, ReductionAudit, ResidualChainBalance, Z4, best_lower_approximation, compose_transitions, crest_braid, descent_reduces_to_best_lower, distinction_set, minimal_distinguishers, observer_by_name, observer_descent, observer_response_map, pullback_observer, pullback_pairs, residual_chain_balance, response_trace, snapshot_doctrine, snapshot_observer, snapshot_transition, transition_map, validate_doctrine, z4_closed_crest_braid, z4_doctrine, z4_parity_descent, z4_reduction_audit, z4_shift, z4_successor, z4_threshold_descent, z4_two_tact_balance
from .observer.gap_topology import FiniteDAG, FiniteSeparationTheoremCard, ObserverClassDefinition, TopologicalOrderSeparationRow, base_witness_graphs, finite_topological_separation_theorem, observer_class_definitions, observer_gap_topology_summary, topological_baseline_signature, topological_order_count, topological_order_separation_family
from .observer.patch_atlas import ExactGluingCriterion, LocalContradiction, LocalObserverSection, ObserverPatch, ObserverPatchAtlas, PairwiseOverlapRow, TriangleCounterexample, exact_gluing_criterion, exact_gluing_relation, generated_echo_closure, local_contradictions, local_echo_relation, local_observer_section, observer_patch, observer_patch_atlas, pairwise_overlap_rows, triangle_counterexample
from .construction.infinity_prefix import PrefixAlphabet, PrefixCoherenceReport, PrefixRestrictionObstruction, PrefixStage, PrefixTowerWindow, first_prefix_obstruction, periodic_prefix_window, prefix_alphabet, prefix_coherence_report, prefix_stage, prefix_tower_window, restrict_prefix
from .padic.residue_tower import PadicCoherenceReport, PadicCompatibilityObstruction, PadicResidueStage, PadicResidueWindow, PrimeBase, add_padic_windows, first_padic_obstruction, integer_padic_window, multiply_padic_windows, padic_coherence_report, padic_residue_stage, padic_residue_window, prime_base, project_padic_stage
from .ontology.core import presentation_commitment, continuation_witness, observer_support_judgment, family_extension_judgment, internal_observer, metalanguage_boundary, ontology_presentation, ontology_stage, persistence_judgment, silence_modalities
from .ontology.boundaries import bounded_window_judgment, diagram_coherence_judgment, local_extension_judgment, nonfinite_infinity_boundary, positive_ontology_checklist, silence_boundary_judgment
from .ontology.facets import ontology_facet_report
from .ontology.doctrine import observer_doctrine, p0_observer_doctrine
from .ontology.types import PresentationCommitment, ContinuationWitness, DiagramCoherenceJudgment, ObserverSupportJudgment, ObserverSupport, FacetStatus, FamilyExtensionJudgment, InfinityJudgment, InfinityLevel, InternalObserver, MetalanguageBoundary, ObserverDoctrine, OntologyFacetReport, OntologyPresentation, OntologyStage, PersistenceJudgment, RelationObstruction, RelationStatus, RunJudgment, RunStatus, SilenceBoundaryJudgment, SilenceModality
from .observer.morphism import ComparisonDomain, InformationLoss, MorphismStatus, ObserverMorphismJudgment, ObserverMorphismValidationError, ObserverSourceBinding, ProjectionStep, R11DomainProfile, ResponseTranslation, compose_observer_morphisms, identity_observer_morphism, observer_morphism_judgment, observer_source_binding, p1a_observer_morphism_doctrine, r11_domain_profile, translate_response
from .construction.finite_builder.runtime import FiniteBuilderReplayError, replay_finite_builder, snapshot_replay_artifact
from .construction.finite_builder.types import ConstructionSourceBinding, FiniteBuilderProgram, FiniteConstructionJudgment, FiniteRecurrenceSeed, FormalGenerability, OnticGenesis, PulseStep, ReplayArtifact, ReplayStatus, ScopedObjectFormation, SeedRef, TargetIndependence
from .construction.finite_builder.validation import FiniteBuilderValidationError
from .construction.finite_construction import compose_finite_builder_expressions, construction_source_binding, finite_builder_program, finite_construction_judgment, finite_recurrence_seed, validate_finite_construction_judgment
from .confluence import compose_diagram_paths, diagram_edge, diagram_path, direct_echo_transport, finite_diagram_source, fork_confluence_judgment, fork_join_plan, replay_diagram_path, swap_fork_join_plan
from .confluence.preflight import ConfluenceValidationError, MAX_CONFLUENCE_CHECKS, preflight_confluence_checks
from .confluence.types import AlignmentPoint, ConfluenceObstruction, ConfluencePreflightCharge, ConfluenceStatus, DiagramEdge, DiagramPath, DiagramPathReplay, DirectEchoTransport, FiniteDiagramSource, ForkConfluenceJudgment, ForkJoinPlan, HigherConfluence, ScopedFormation, Transport2CellArtifact, TransportMode, TransportResponseRow
from .construction.productivity.core import OUTPUT_ENCODING_ID, POLICY_VERSION, PROGRAM_VERSION, RESTRICTION_LAW_ID, TOTALITY_BASIS_ID, construct_at_depth, execution_policy, periodic_program, productive_process_source, restriction_judgment, validate_construction_result, validate_restriction_result
from .construction.productivity.types import AllDepthEvidenceStatus, AllDepthProvenance, CompletedCarrierStatus, ConstructionArtifact, ConstructionResult, ExecutionPolicy, OperationKind, OperationStatus, PeriodicPrefixStage, PeriodicProgram, PointwiseSchemaStatus, PointwiseStatus, ProductiveProcessSource, ProductivityStatus, ResourceBound, ResourceLimitResult, RestrictionArtifact, RestrictionResult, StructuralGuardedness
from .construction.productivity.validation import ProductivityValidationError
from .observer.genesis.core import ADAPTER_ID, CLOSURE_LAW_ID, GENEALOGY_VERSION, OEP_PRINCIPLE_ID, RECURRENCE_LAW_ID, derive_fixed_machine, genesis_resource_policy, mode_genealogy, observer_genesis_doctrine, observer_genesis_judgment, observer_genesis_source, oep_admission_record, origin_mode_spec, recurrence_witness, unavailable_recurrence, validate_genesis_result, witness_scope
from .observer.genesis.native import ObserverGenesisValidationError
from .observer.genesis.types import BreathSpec, FiniteObserverMachine, GenesisJudgment, GenesisOperation, GenesisOperationStatus, GenesisResourceBound, GenesisResourceLimit, GenesisResourcePolicy, GenesisResult, HistoricalTargetIndependence, MachineState, ModeSpec, NodSpec, OEPAdmission, OEPAdmissionRecord, ObserverGenesisDoctrine, ObserverGenesisSource, ObserverRole, PhysicalInstantiation, PremiseArtifact, PremiseName, PremiseStatus, RecurrenceEvidence, RecurrenceWitness, RezSpec, TactSpec, TransitionRow, UnavailableRecurrenceEvidence, WitnessScope
from .observer.relations.core import ComparisonMode, CoverageStatus, DomainWitness, InvertibilityStatus, LawStatus, LossStatus, MorphismEvidenceStatus, MorphismReplaySpec, OBSERVER_RELATION_NONCLAIMS, ObserverRelationJudgment, ObserverRelationResult, ObserverRelationScope, ObserverRelationValidationError, PairOutcome, ProposalStatus, RelationClass, RelationEvaluationSource, RelationOperation, RelationPairRow, RelationResourceLimit, RelationResourcePolicy, RelationResultStatus, RelationRunStatus, RelationStage, RelationWitness, StageObservationRow, TranslationAssessment, TranslationInputKind, TranslationProposal, TranslationTriangleRow, morphism_replay_spec, observer_relation_judgment, observer_relation_scope, observer_relations_scope_boundary, relation_evaluation_source, relation_resource_policy, replay_observer_relation, translation_proposal, validate_observer_relation_result
from .construction.productivity.counterpressure import ALPHABET_VERSION as COUNTERPRESSURE_ALPHABET_VERSION, ARTIFACT_NAME as COUNTERPRESSURE_ARTIFACT_NAME, ARTIFACT_SHA256 as COUNTERPRESSURE_ARTIFACT_SHA256, BASIS_ID as COUNTERPRESSURE_BASIS_ID, DEFAULT_POLICY as DEFAULT_COUNTERPRESSURE_POLICY, FOUNDATION_ID as COUNTERPRESSURE_FOUNDATION_ID, LEAN_TCB_DIGEST as COUNTERPRESSURE_LEAN_TCB_DIGEST, LEAN_TOOLCHAIN_ID as COUNTERPRESSURE_LEAN_TOOLCHAIN_ID, MAX_REQUEST_BYTES as COUNTERPRESSURE_MAX_REQUEST_BYTES, MAX_SYMBOLIC_COST as COUNTERPRESSURE_MAX_SYMBOLIC_COST, POLICY_VERSION as COUNTERPRESSURE_POLICY_VERSION, REQUEST_VERSION as COUNTERPRESSURE_REQUEST_VERSION, THEOREM_IDS as COUNTERPRESSURE_THEOREM_IDS, CompletedCarrierStatus as CounterpressureCompletedCarrierStatus, HistoricalTargetIndependence as CounterpressureHistoricalTargetIndependence, AllDepthFamilyStatus, BasisUse, ChooserTargetIndependence, CounterpressureAlphabet, CounterpressureBasisSource, CounterpressureCertificate, CounterpressureEvidence, CounterpressureInference, CounterpressureOutcomeKind, CounterpressurePolicy, CounterpressureRequest, CounterpressureRequestKind, CounterpressureResourceBound, CounterpressureResourceLimit, CounterpressureResult, CounterpressureStatus, CounterpressureValidationError, DecreasingTreeRequest, DerivationKind, DescentCountermodelEvidence, FiniteRunInsufficiencyEvidence, GeneratorNonexistence, LedgerInsufficiencyEvidence, LedgerRow, LongRunRequest, NonuniformLedgerRequest, ShrinkingStageRequest, ShrinkingTailCountermodelEvidence, TargetChooserRequest, TargetDependenceEvidence, check_basis_source, counterpressure_alphabet, counterpressure_basis_source, counterpressure_policy, counterpressure_result, decreasing_tree_request, ledger_request, long_run_request, shrinking_stage_request, target_chooser_request, validate_counterpressure_result
from .confluence.aggregate import AggregateCoverageStatus, AggregateFailedBound, AggregateResultStatus, C2_NONCLAIMS, ConfluenceAggregatePolicy, ConfluenceAggregateResourceLimit, ConfluenceRequirementRow, DeclaredHistory, FiniteConfluenceAggregate, FiniteConfluenceCatalogSource, FiniteConfluenceResult, GlobalDeclaredFiniteStatus, GlobalHistory2CellArtifact, GlobalPathPairRequirement, IdentityHistory, LocalCriticalForkRequirement, LocalFiniteStatus, RequirementKind, confluence_aggregate_policy, confluence_aggregate_scope_boundary, declared_history, finite_confluence_aggregate, finite_confluence_catalog, global_path_pair_requirement, identity_history, local_critical_fork_requirement, validate_finite_confluence_result
from .construction.all_depth_family.core import ARTIFACT_NAME as D3_ARTIFACT_NAME, ARTIFACT_SHA256 as D3_ARTIFACT_SHA256, AXIOM_CLOSURE as D3_AXIOM_CLOSURE, LEAN_TCB_DIGEST as D3_LEAN_TCB_DIGEST, LEAN_TOOLCHAIN_ID as D3_LEAN_TOOLCHAIN_ID, THEOREM_IDS as D3_THEOREM_IDS, AllDepthFamilyValidationError, ORACLE_CONSTRUCTOR_ID, ORACLE_PURITY_HYPOTHESIS_ID, ORACLE_STABILITY_HYPOTHESIS_ID, ORACLE_TOTALITY_HYPOTHESIS_ID, PERIODIC_CONSTRUCTOR_ID, SUPPLIED_COMPATIBILITY_LAW_ID, SUPPLIED_CONSTRUCTOR_ID, SUPPLIED_COORDINATE_LAW_ID, admit_oracle_family, admit_supplied_family, all_depth_family_spec, assess_family_law_counterexample, assumption_ledger, assumption_row, check_formal_source, derive_periodic_family, finite_family_law_witness, hypothesis_family_ledger, open_all_depth_family, oracle_family_hypothesis, periodic_family_formal_source, periodic_family_ledger, periodic_family_term, project_family_stage, relation_edge, replay_all_depth_family, restriction_row, supplied_family_hypothesis, symbolic_family_term, validate_derived_family_judgment, validate_family_law_counterexample_assessment, validate_family_projection, validate_open_family_judgment, validate_oracle_family_judgment, validate_supplied_family_judgment
from .construction.all_depth_family.types import AlgebraicLawStatus, AllDepthFamilyJudgment, AllDepthFamilySpec, AssumptionKind, AssumptionLedger, AssumptionRow, CompletedCarrierStatus as FamilyCompletedCarrierStatus, FamilyEvidenceStatus, FamilyHypothesis, FamilyIntroductionSource, FamilyProjectionArtifact, FamilyProjectionRefusal, FamilyProvenance, FamilyTerm, FormalFamilySource, HigherStatus, IntroductionKind, LawStatus as FamilyLawStatus, LedgerStatus, OracleFamilyHypothesis, ProjectionCapability, ProjectionResourceBound, ProjectionStatus
from .construction.all_depth_family.counterexample import CounterexampleLawVector, FamilyLaw, FamilyLawCounterexampleAssessment, FamilyNonexistence, FiniteFamilyLawWitness, RelationEdge, RestrictionRow
from .confluence.translated.core import C3TransportMode, C3TransportSpec, ObserverProgramBridgeRow, P0P1AResponseBridgeSource, StageInputBridgeRow, TRANSLATED_CONFLUENCE_NONCLAIMS, TranslatedConfluenceJudgment, TranslatedConfluencePolicy, TranslatedConfluenceResourceLimit, TranslatedConfluenceResult, TranslatedConfluenceValidationError, TranslatedEchoTransportSpec, TranslatedResponseRow, TranslatedResourceBound, TranslatedResourceSource, TranslatedTransport2CellArtifact, TranslationDirection, c3_confluence_judgment, p0_p1a_response_bridge, translated_confluence_judgment, translated_confluence_policy, translated_echo_transport_spec, validate_translated_confluence_result
from .construction.stream_completion.core import ARTIFACT_PATH as POMEGA1_ARTIFACT_PATH, ARTIFACT_SHA256 as POMEGA1_ARTIFACT_SHA256, AXIOM_CLOSURE as POMEGA1_AXIOM_CLOSURE, BRIDGE_THEOREM_IDS as POMEGA1_BRIDGE_THEOREM_IDS, SCP_THEOREM_IDS as POMEGA1_SCP_THEOREM_IDS, StreamCompletionValidationError, TCB_DIGEST as POMEGA1_TCB_DIGEST, THEOREM_IDS as POMEGA1_THEOREM_IDS, TOOLCHAIN_ID as POMEGA1_TOOLCHAIN_ID, bounded_stream_shadow, formal_alphabet_presentation, stream_alphabet_source, stream_completion_doctrine as pomega1_stream_completion_doctrine, stream_completion_judgment, stream_completion_ledger as pomega1_stream_completion_ledger, stream_completion_package as pomega1_stream_completion_package, stream_completion_policy, stream_completion_theorem_source, validate_stream_completion_result
from .construction.stream_completion.types import BoundedStreamShadow, CompletedCarrierStatus as StreamCompletedCarrierStatus, CompletionFailedBound as StreamCompletionFailedBound, CompletionObligationStatuses as StreamCompletionObligationStatuses, CompletionResultStatus as StreamCompletionResultStatus, FormalAlphabetPresentation, FormalExecutionFailure as StreamFormalExecutionFailure, FormalExecutionFailureKind as StreamFormalExecutionFailureKind, LedgerRowClass as StreamLedgerRowClass, MetaphysicalTotalityStatus as StreamMetaphysicalTotalityStatus, ObligationStatus as StreamObligationStatus, POMEGA1_NONCLAIMS, PhysicalInstantiationStatus as StreamPhysicalInstantiationStatus, StreamAlphabetSource, StreamCompletionDoctrine, StreamCompletionJudgment, StreamCompletionLedger, StreamCompletionLedgerRow, StreamCompletionPackage, StreamCompletionPolicy, StreamCompletionResourceLimit, StreamCompletionResult, StreamCompletionTheoremSource
from .registry.status_promotion import public as _status_promotion_public
from .registry.status_promotion.public import *  # noqa: F403
from .construction.scoped_formation import public as _scoped_formation_public
from .construction.scoped_formation.public import *  # noqa: F403
from .observer.actualization import public as _observer_actualization_public
from .observer.actualization.public import *  # noqa: F403
from .confluence.generated import public as _generated_confluence_public
from .confluence.generated.public import *  # noqa: F403
from .padic.completion import public as _padic_completion_public
from .padic.completion.public import *  # noqa: F403
from .padic.family_introduction import public as _padic_family_introduction_public
from .padic.family_introduction.public import *  # noqa: F403
from .observer.network import public as _observer_network_public
from .observer.network.public import *  # noqa: F403
from .prime_power.productive_bridge import public as _prime_power_productive_bridge_public
from .prime_power.productive_bridge.public import *  # noqa: F403
from .prime_power.reduction_network import public as _prime_power_reduction_network_public
from .prime_power.reduction_network.public import *  # noqa: F403
from .padic.local_realization import public as _padic_local_realization_public
from .padic.local_realization.public import *  # noqa: F403
from .transport import public as _transport_coherence_public
from .transport.public import *  # noqa: F403
from .quantum.tensor_semantics import UnitarityWitness, adjoint, apply_unitary, born_distribution, born_total, conjugate, inner_product, is_normalized, tensor_gates, tensor_modes, unitarity_witness

__all__ = [
    "DerivationReceipt", "ReceiptCheck", "SemanticResult", "axiom_closure", "evaluate_native", "observer_adapter", "replay_receipts", "verify_receipts", "LayerDerivation", "LayerDerivationReport", "layer_derivation_report", "layer_derivations", "NativeFormalBridgeReport", "intrinsic_arithmetic_lean_status", "native_formal_bridge_report",
    "DivisionStep", "EscapeWitness", "ProductPlusOneObstructionProof", "StructuralDivisionProof", "intrinsic_arithmetic_summary", "mode_power", "one", "one_mode", "power", "product_plus_one_escape", "product_plus_one_obstruction", "structural_divide", "structural_division", "successor", "weave", "zero", "zero_mode",
    "CandidateEvaluation", "FittedObserver", "HoldoutReport", "NamedBaseline", "ObserverCase", "ObserverCaseEvidence", "ObserverGrammar", "ObserverPrimitive", "ObserverResponse", "ObserverSynthesisResult", "ObserverTerm", "SynthesisConfig", "SynthesisObstruction", "canonical_term", "enumerate_observer_terms", "evaluate_observer", "fit_observer", "observer_fingerprint", "observer_term_cost", "score_observer", "synthesize_observer", "validate_observer", "StrictObserverClassCertificate", "observer_synthesis_summary", "observer_term_text", "parity_baselines", "parity_holdout_cases", "parity_observer_grammar", "parity_observer_synthesis", "parity_table", "parity_train_cases", "proper_marginal_signature", "strict_observer_class_certificate", "xor_rows",
    "ClassicalBenchmarkCard", "classical_benchmark_cards", "classical_benchmark_checklist", "classical_benchmark_summary",
    "BenchmarkDerivationRow", "DeductionLink", "DeductionProofRow", "NativeRightCornerRow", "deduction_chain_checklist", "deduction_chain_summary", "deduction_links", "deduction_proof_rows", "benchmark_derivation_checklist", "benchmark_derivation_rows", "benchmark_derivation_summary", "derive_benchmark_verdict",
    "EuclidEscapeRow", "NativeEuclidModeRow", "NativeFermatPhaseRow", "euclid_escape_row", "lean_euclid_bridge_ready", "native_euclid_mode_row", "native_euclid_mode_rows", "native_euclid_rows", "native_fermat_obstruction_rows", "native_fermat_phase_row", "native_fermat_phase_rows", "native_number_theorem_gaps", "native_number_theorem_summary", "native_axis_breath", "native_geometry_derivation_rows", "native_geometry_derivation_summary", "native_right_corner_row",
    "AxiomKernelReport", "AxiomWitness", "KernelAxiom", "LayerAxiomUse", "axiom_kernel_checklist", "axiom_kernel_report", "axiom_witness_rows", "layer_axiom_dependencies", "unified_axiom_kernel",
    "FormalProofCertificate", "FormalProofStep", "LeanCheckResult", "FormalExportCompletionRow", "FormalExportPrepRow", "check_formal_proof", "check_lean_echo_export", "checked_bridge_rows", "echo_reflexive_certificate", "echo_reflexive_proof_steps", "formal_bridge_checklist", "formal_bridge_summary", "AREA_ADDITIVITY_ID", "AREA_ADDITIVITY_SYMBOL", "CHORD_SYMMETRY_ID", "CHORD_SYMMETRY_SYMBOL", "DRIFT_STABILITY_ID", "DRIFT_STABILITY_SYMBOL", "SAMPLED_CONTINUITY_ID", "SAMPLED_CONTINUITY_SYMBOL", "area_additivity_completion_row", "binomial_symmetry_completion_row", "chord_symmetry_completion_row", "completed_formal_export_rows", "cyclic_period_completion_row", "drift_stability_completion_row", "formal_export_completion_checklist", "formal_export_completion_summary", "formal_export_prep_checklist", "formal_export_prep_rows", "formal_export_prep_summary", "lean_algebra_export_path", "lean_combinatorics_export_path", "lean_cyclic_period_export_path", "lean_echo_export_path", "lean_probability_export_path", "lean_pythagorean_export_path", "lean_statistics_export_path", "line_shell_intersection_completion_row", "linear_equation_completion_row", "mean_balance_completion_row", "plane_relabel_composition_completion_row", "polynomial_evaluation_completion_row", "polynomial_identity_completion_row", "probability_complement_completion_row", "probability_independence_completion_row", "probability_union_completion_row", "pythagorean_separation_completion_row", "sampled_continuity_completion_row", "sas_triangle_completion_row", "sss_triangle_completion_row", "stable_card_export_prep_rows", "variance_shift_completion_row",
    "ProofObligation", "TheoremCheck", "TheoremEnvironment", "TheoremProposition", "TheoremQuantifier", "TheoremStatement", "check_theorem_statement", "default_theorem_environments", "parse_theorem_statement", "theorem_language_checklist", "theorem_obligation_rows",
    "VeyraSpanCoverageReport", "VeyraSpanDiagnosticCase", "VeyraSpanDiagnosticResult", "missed_span_diagnostic_rules", "run_span_diagnostic_case", "run_span_diagnostic_coverage", "span_diagnostic_cases", "span_diagnostic_coverage_checklist", "span_diagnostic_coverage_report",
    "TrigIdentityVector", "compose_phases", "conjugate_phase", "double_angle_identity_card", "inverse_phase_identity_card", "pythagorean_identity_card", "sum_angle_identity_card", "trig_vector_from_ints", "trigonometry_identity_checklist", "unit_identity_gap",
    "PhaseCoordinateRow", "PhasePairRow", "default_phase_basis", "inverse_phase_obstruction_card", "phase_coordinate_row", "phase_equation_checklist", "phase_equation_normal_form_card", "phase_pair_row", "QuantumErrorObstructionRow", "branch_distinguishability_row", "interference_loss_row", "leakage_row", "nonunitarity_row", "phase_break_row", "quantum_error_obstruction_checklist", "quantum_error_obstruction_rows", "quantum_error_obstruction_summary", "syndrome_ambiguity_row", "GateIdentityBaselineRow", "GateIdentityRow", "cnot_conjugation_rows", "gate_equal", "gate_identity_baseline_rows", "gate_identity_rows", "gate_phase_equal", "gate_word", "q_gate_i2", "q_gate_s", "q_gate_z", "quantum_gate_identity_checklist", "quantum_gate_identity_summary", "scale_gate", "QECAmbiguityRow", "QECBranchRow", "QECObserverFamilyRow", "QECSplitEchoRow", "branch_shadow", "qec_ambiguity_rows", "qec_branch", "qec_branch_rows", "qec_echo", "qec_observer_family_rows", "qec_split_echo_rows", "quantum_qec_echo_checklist", "quantum_qec_echo_summary", "QFTOffsetEchoRow", "QFTPeriodObstructionRow", "QFTPeriodRow", "expected_period_frequencies", "observed_frequencies", "phase_orbit", "qft4_gate", "qft_offset_echo_row", "qft_period_obstruction_row", "qft_period_row", "qft_period_rows", "qft_period_state", "qft_shadow", "quantum_qft_period_checklist", "quantum_qft_period_summary", "QBraidOrderRow", "QTopoEchoRow", "QTopoLogicalRow", "QTopoObstructionRow", "VTopoQubit", "braid_shadow", "loop_action", "qbraid_order_rows", "qtopo_echo", "qtopo_echo_rows", "qtopo_logical_rows", "qtopo_obstruction_rows", "quantum_topology_checklist", "quantum_topology_summary", "topo_broken_shape", "topo_deformed_shape", "topo_shape", "topo_signature", "vtopo_qubit", "CircuitCompressionRow", "circuit_compression_checklist", "circuit_compression_rows", "circuit_compression_summary", "QuantumBaselineRow", "quantum_baseline_checklist", "quantum_baseline_rows", "quantum_baseline_summary", "apply_x", "correction_for_syndrome", "logical_observer", "logical_obstruction_rows", "pauli_x_rows", "quantum_stabilizer_checklist", "quantum_stabilizer_summary", "stabilizer_echo_rows", "syndrome", "syndrome_rows", "bell_state", "compose_gate", "is_product_factorable_2q", "observer_distribution", "q_basis_state", "q_gate_cnot", "q_gate_h", "q_gate_i", "q_gate_x", "qecho", "quantum_theorem_cards", "quantum_veyra_checklist", "quantum_veyra_summary", "tensor_gate",
    "LogicalObstructionRow", "PauliRow", "StabilizerEchoRow", "SyndromeRow", "QAmp", "QGate", "QMode", "QuantumTheoremCard", "Rad2", "FormalSeriesShadow", "LimitEnvelope", "alternating_log1p_envelope", "alternating_tail_bound_card", "exp_derivative_card", "exp_series", "factorial_int", "geometric_alt_series", "log1p_derivative_card", "log1p_series", "series_value", "transcendental_limit_checklist",
    "CauchyTailCertificate", "MajorantBound", "NestedIntervalCertificate", "RadiusGuard", "cauchy_tail_card", "cauchy_tail_certificate", "convergence_algebra_checklist", "majorant_bound", "majorant_bound_card", "nested_interval_card", "nested_interval_certificate", "radius_guard", "radius_guard_card", "ratio_abs_distance",
    "FiniteModulusCertificate", "RefinementStabilityCertificate", "area_refinement_certificate", "derivative_refinement_certificate", "finite_modulus_certificate", "identity_rule", "jump_obstruction_card", "jump_rule", "real_analysis_structure_checklist", "square_rule",
    "AdditivityRow", "CoverageRow", "PushForwardRow", "WeightedEchoAtom", "WeightedEchoMeasure", "coverage_row", "finite_additivity_row", "mass_of", "overlap_gap_card", "pushforward_by_tact", "weighted_echo_measure", "weighted_measure_checklist",
    "ConservationRow", "DiffusionRow", "FlowBalanceRow", "FlowEdge", "anti_diffusion_obstruction_card", "finite_conservation_row", "finite_diffusion_row", "finite_flow_balance_row", "ratio_total", "ratio_variation", "science_certificate_checklist",
    "ModelComparisonRow", "ModelFitReport", "ModelObservation", "ResidualRow", "absolute_ratio", "anomaly_obstruction_card", "baseline_model_observations", "canonical_model_observations", "compare_model_reports", "model_diagnostics_checklist", "model_fit_report", "residual_row",
    "CyclicDepthCertificate", "ScaleMemoryLogCertificate", "TransitionDepthRow", "finite_field_log_fixture", "recover_cyclic_depth", "recover_transition_depth", "residual_ratio", "scale_memory_log_checklist", "scale_memory_obstruction_card", "transition_depth_rows",
    "InvariantRow", "MorphismClosureRow", "UniversalShadowRow", "VeyraMorphism", "VeyraObject", "category_closure_rows", "category_invariant_rows", "category_like_checklist", "category_like_examples", "category_like_morphisms", "category_like_summary", "category_universal_shadow_rows", "compose_morphisms", "morphism_closure_row", "morphism_graph", "ratio_object",
    "DeformationEchoRow", "EchoShape", "TopologyObstructionCard", "deformation_echo_row", "deform_shape", "echo_shape", "invariant_value", "subdivide_corridor", "topology_echo_checklist", "topology_echo_shapes", "topology_echo_summary", "topology_invariant_rows", "topology_obstruction_cards",
    "ExactGluingCriterion", "LocalContradiction", "LocalObserverSection", "ObserverPatch", "ObserverPatchAtlas", "PairwiseOverlapRow", "TriangleCounterexample", "exact_gluing_criterion", "exact_gluing_relation", "generated_echo_closure", "local_contradictions", "local_echo_relation", "local_observer_section", "observer_patch", "observer_patch_atlas", "pairwise_overlap_rows", "triangle_counterexample",
    "PrefixAlphabet", "PrefixCoherenceReport", "PrefixRestrictionObstruction", "PrefixStage", "PrefixTowerWindow", "first_prefix_obstruction", "periodic_prefix_window", "prefix_alphabet", "prefix_coherence_report", "prefix_stage", "prefix_tower_window", "restrict_prefix", "PadicCoherenceReport", "PadicCompatibilityObstruction", "PadicResidueStage", "PadicResidueWindow", "PrimeBase", "add_padic_windows", "first_padic_obstruction", "integer_padic_window", "multiply_padic_windows", "padic_coherence_report", "padic_residue_stage", "padic_residue_window", "prime_base", "project_padic_stage",
    "PresentationCommitment", "ContinuationWitness", "DiagramCoherenceJudgment", "ObserverSupportJudgment", "ObserverSupport", "FacetStatus", "FamilyExtensionJudgment", "InfinityJudgment", "InfinityLevel", "InternalObserver", "MetalanguageBoundary", "ObserverDoctrine", "OntologyFacetReport", "OntologyPresentation", "OntologyStage", "PersistenceJudgment", "RelationObstruction", "RelationStatus", "RunJudgment", "RunStatus", "SilenceBoundaryJudgment", "SilenceModality", "bounded_window_judgment", "presentation_commitment", "continuation_witness", "diagram_coherence_judgment", "observer_support_judgment", "family_extension_judgment", "internal_observer", "local_extension_judgment", "metalanguage_boundary", "nonfinite_infinity_boundary", "observer_doctrine", "ontology_facet_report", "ontology_presentation", "ontology_stage", "p0_observer_doctrine", "persistence_judgment", "positive_ontology_checklist", "silence_boundary_judgment", "silence_modalities", "ComparisonDomain", "InformationLoss", "MorphismStatus", "ObserverMorphismJudgment", "ObserverMorphismValidationError", "ObserverSourceBinding", "ProjectionStep", "R11DomainProfile", "ResponseTranslation", "compose_observer_morphisms", "identity_observer_morphism", "observer_morphism_judgment", "observer_source_binding", "p1a_observer_morphism_doctrine", "r11_domain_profile", "translate_response", "ConstructionSourceBinding", "FiniteBuilderProgram", "FiniteBuilderReplayError", "FiniteBuilderValidationError", "FiniteConstructionJudgment", "FiniteRecurrenceSeed", "FormalGenerability", "OnticGenesis", "PulseStep", "ReplayArtifact", "ReplayStatus", "ScopedObjectFormation", "SeedRef", "TargetIndependence", "compose_finite_builder_expressions", "construction_source_binding", "finite_builder_program", "finite_construction_judgment", "finite_recurrence_seed", "replay_finite_builder", "snapshot_replay_artifact", "validate_finite_construction_judgment", "AlignmentPoint", "ConfluenceObstruction", "ConfluencePreflightCharge", "ConfluenceStatus", "ConfluenceValidationError", "DiagramEdge", "DiagramPath", "DiagramPathReplay", "DirectEchoTransport", "FiniteDiagramSource", "ForkConfluenceJudgment", "ForkJoinPlan", "HigherConfluence", "MAX_CONFLUENCE_CHECKS", "ScopedFormation", "Transport2CellArtifact", "TransportMode", "TransportResponseRow", "compose_diagram_paths", "diagram_edge", "diagram_path", "direct_echo_transport", "finite_diagram_source", "fork_confluence_judgment", "fork_join_plan", "preflight_confluence_checks", "replay_diagram_path", "swap_fork_join_plan",
    "AllDepthEvidenceStatus", "AllDepthProvenance", "CompletedCarrierStatus", "ConstructionArtifact", "ConstructionResult", "ExecutionPolicy", "OperationKind", "OperationStatus", "OUTPUT_ENCODING_ID", "POLICY_VERSION", "PROGRAM_VERSION", "PeriodicPrefixStage", "PeriodicProgram", "PointwiseSchemaStatus", "PointwiseStatus", "ProductiveProcessSource", "ProductivityStatus", "ProductivityValidationError", "RESTRICTION_LAW_ID", "ResourceBound", "ResourceLimitResult", "RestrictionArtifact", "RestrictionResult", "StructuralGuardedness", "TOTALITY_BASIS_ID", "construct_at_depth", "execution_policy", "periodic_program", "productive_process_source", "restriction_judgment", "validate_construction_result", "validate_restriction_result",
    "ADAPTER_ID", "BreathSpec", "CLOSURE_LAW_ID", "FiniteObserverMachine", "GENEALOGY_VERSION", "GenesisJudgment", "GenesisOperation", "GenesisOperationStatus", "GenesisResourceBound", "GenesisResourceLimit", "GenesisResourcePolicy", "GenesisResult", "HistoricalTargetIndependence", "MachineState", "ModeSpec", "NodSpec", "OEPAdmission", "OEPAdmissionRecord", "OEP_PRINCIPLE_ID", "ObserverGenesisDoctrine", "ObserverGenesisSource", "ObserverGenesisValidationError", "ObserverRole", "PhysicalInstantiation", "PremiseArtifact", "PremiseName", "PremiseStatus", "RECURRENCE_LAW_ID", "RecurrenceEvidence", "RecurrenceWitness", "RezSpec", "TactSpec", "TransitionRow", "UnavailableRecurrenceEvidence", "WitnessScope", "derive_fixed_machine", "genesis_resource_policy", "mode_genealogy", "observer_genesis_doctrine", "observer_genesis_judgment", "observer_genesis_source", "oep_admission_record", "origin_mode_spec", "recurrence_witness", "unavailable_recurrence", "validate_genesis_result", "witness_scope",
    "ComparisonMode", "CoverageStatus", "DomainWitness", "InvertibilityStatus", "LawStatus", "LossStatus", "MorphismEvidenceStatus", "MorphismReplaySpec", "OBSERVER_RELATION_NONCLAIMS", "ObserverRelationJudgment", "ObserverRelationResult", "ObserverRelationScope", "ObserverRelationValidationError", "PairOutcome", "ProposalStatus", "RelationClass", "RelationEvaluationSource", "RelationOperation", "RelationPairRow", "RelationResourceLimit", "RelationResourcePolicy", "RelationResultStatus", "RelationRunStatus", "RelationStage", "RelationWitness", "StageObservationRow", "TranslationAssessment", "TranslationInputKind", "TranslationProposal", "TranslationTriangleRow", "morphism_replay_spec", "observer_relation_judgment", "observer_relation_scope", "observer_relations_scope_boundary", "relation_evaluation_source", "relation_resource_policy", "replay_observer_relation", "translation_proposal", "validate_observer_relation_result",
    "AllDepthFamilyStatus", "BasisUse", "ChooserTargetIndependence", "COUNTERPRESSURE_ALPHABET_VERSION", "COUNTERPRESSURE_ARTIFACT_NAME", "COUNTERPRESSURE_ARTIFACT_SHA256", "COUNTERPRESSURE_BASIS_ID", "COUNTERPRESSURE_FOUNDATION_ID", "COUNTERPRESSURE_LEAN_TCB_DIGEST", "COUNTERPRESSURE_LEAN_TOOLCHAIN_ID", "COUNTERPRESSURE_MAX_REQUEST_BYTES", "COUNTERPRESSURE_MAX_SYMBOLIC_COST", "COUNTERPRESSURE_POLICY_VERSION", "COUNTERPRESSURE_REQUEST_VERSION", "COUNTERPRESSURE_THEOREM_IDS", "CounterpressureCompletedCarrierStatus", "CounterpressureHistoricalTargetIndependence", "CounterpressureAlphabet", "CounterpressureBasisSource", "CounterpressureCertificate", "CounterpressureEvidence", "CounterpressureInference", "CounterpressureOutcomeKind", "CounterpressurePolicy", "CounterpressureRequest", "CounterpressureRequestKind", "CounterpressureResourceBound", "CounterpressureResourceLimit", "CounterpressureResult", "CounterpressureStatus", "CounterpressureValidationError", "DEFAULT_COUNTERPRESSURE_POLICY", "DecreasingTreeRequest", "DerivationKind", "DescentCountermodelEvidence", "FiniteRunInsufficiencyEvidence", "GeneratorNonexistence", "LedgerInsufficiencyEvidence", "LedgerRow", "LongRunRequest", "NonuniformLedgerRequest", "ShrinkingStageRequest", "ShrinkingTailCountermodelEvidence", "TargetChooserRequest", "TargetDependenceEvidence", "check_basis_source", "counterpressure_alphabet", "counterpressure_basis_source", "counterpressure_policy", "counterpressure_result", "decreasing_tree_request", "ledger_request", "long_run_request", "shrinking_stage_request", "target_chooser_request", "validate_counterpressure_result",
    "AggregateCoverageStatus", "AggregateFailedBound", "AggregateResultStatus", "C2_NONCLAIMS", "ConfluenceAggregatePolicy", "ConfluenceAggregateResourceLimit", "ConfluenceRequirementRow", "DeclaredHistory", "FiniteConfluenceAggregate", "FiniteConfluenceCatalogSource", "FiniteConfluenceResult", "GlobalDeclaredFiniteStatus", "GlobalHistory2CellArtifact", "GlobalPathPairRequirement", "IdentityHistory", "LocalCriticalForkRequirement", "LocalFiniteStatus", "RequirementKind", "confluence_aggregate_policy", "confluence_aggregate_scope_boundary", "declared_history", "finite_confluence_aggregate", "finite_confluence_catalog", "global_path_pair_requirement", "identity_history", "local_critical_fork_requirement", "validate_finite_confluence_result",
    "AlgebraicLawStatus", "AllDepthFamilyJudgment", "AllDepthFamilySpec", "AllDepthFamilyValidationError", "AssumptionKind", "AssumptionLedger", "AssumptionRow", "CounterexampleLawVector", "D3_ARTIFACT_NAME", "D3_ARTIFACT_SHA256", "D3_AXIOM_CLOSURE", "D3_LEAN_TCB_DIGEST", "D3_LEAN_TOOLCHAIN_ID", "D3_THEOREM_IDS", "FamilyCompletedCarrierStatus", "FamilyEvidenceStatus", "FamilyHypothesis", "FamilyIntroductionSource", "FamilyLaw", "FamilyLawCounterexampleAssessment", "FamilyLawStatus", "FamilyNonexistence", "FamilyProjectionArtifact", "FamilyProjectionRefusal", "FamilyProvenance", "FamilyTerm", "FiniteFamilyLawWitness", "FormalFamilySource", "HigherStatus", "IntroductionKind", "LedgerStatus", "ORACLE_CONSTRUCTOR_ID", "ORACLE_PURITY_HYPOTHESIS_ID", "ORACLE_STABILITY_HYPOTHESIS_ID", "ORACLE_TOTALITY_HYPOTHESIS_ID", "OracleFamilyHypothesis", "PERIODIC_CONSTRUCTOR_ID", "ProjectionCapability", "ProjectionResourceBound", "ProjectionStatus", "RelationEdge", "RestrictionRow", "SUPPLIED_COMPATIBILITY_LAW_ID", "SUPPLIED_CONSTRUCTOR_ID", "SUPPLIED_COORDINATE_LAW_ID", "admit_oracle_family", "admit_supplied_family", "all_depth_family_spec", "assess_family_law_counterexample", "assumption_ledger", "assumption_row", "check_formal_source", "derive_periodic_family", "finite_family_law_witness", "hypothesis_family_ledger", "open_all_depth_family", "oracle_family_hypothesis", "periodic_family_formal_source", "periodic_family_ledger", "periodic_family_term", "project_family_stage", "relation_edge", "replay_all_depth_family", "restriction_row", "supplied_family_hypothesis", "symbolic_family_term", "validate_derived_family_judgment", "validate_family_law_counterexample_assessment", "validate_family_projection", "validate_open_family_judgment", "validate_oracle_family_judgment", "validate_supplied_family_judgment",
    "C3TransportMode", "C3TransportSpec", "ObserverProgramBridgeRow", "P0P1AResponseBridgeSource", "StageInputBridgeRow", "TRANSLATED_CONFLUENCE_NONCLAIMS", "TranslatedConfluenceJudgment", "TranslatedConfluencePolicy", "TranslatedConfluenceResourceLimit", "TranslatedConfluenceResult", "TranslatedConfluenceValidationError", "TranslatedEchoTransportSpec", "TranslatedResponseRow", "TranslatedResourceBound", "TranslatedResourceSource", "TranslatedTransport2CellArtifact", "TranslationDirection", "c3_confluence_judgment", "p0_p1a_response_bridge", "translated_confluence_judgment", "translated_confluence_policy", "translated_echo_transport_spec", "validate_translated_confluence_result",
    "POMEGA1_ARTIFACT_PATH", "POMEGA1_ARTIFACT_SHA256", "POMEGA1_AXIOM_CLOSURE", "POMEGA1_BRIDGE_THEOREM_IDS", "POMEGA1_NONCLAIMS", "POMEGA1_SCP_THEOREM_IDS", "POMEGA1_TCB_DIGEST", "POMEGA1_THEOREM_IDS", "POMEGA1_TOOLCHAIN_ID", "StreamCompletionValidationError", "bounded_stream_shadow", "formal_alphabet_presentation", "stream_alphabet_source", "pomega1_stream_completion_doctrine", "stream_completion_judgment", "pomega1_stream_completion_ledger", "pomega1_stream_completion_package", "stream_completion_policy", "stream_completion_theorem_source", "validate_stream_completion_result", "BoundedStreamShadow", "StreamCompletedCarrierStatus", "StreamCompletionFailedBound", "StreamCompletionObligationStatuses", "StreamCompletionResultStatus", "FormalAlphabetPresentation", "StreamFormalExecutionFailure", "StreamFormalExecutionFailureKind", "StreamLedgerRowClass", "StreamMetaphysicalTotalityStatus", "StreamObligationStatus", "StreamPhysicalInstantiationStatus", "StreamAlphabetSource", "StreamCompletionDoctrine", "StreamCompletionJudgment", "StreamCompletionLedger", "StreamCompletionLedgerRow", "StreamCompletionPackage", "StreamCompletionPolicy", "StreamCompletionResourceLimit", "StreamCompletionResult", "StreamCompletionTheoremSource",
    "GeometryVisualSnapshot", "VeyraCoreLayer", "VeyraEssenceAxiom", "VeyraEssenceReport", "core_layers", "essence_axioms", "essence_checklist", "essence_report", "geometry_visual_regression_checklist", "geometry_visual_regression_summary", "geometry_visual_scene_rows", "geometry_visual_snapshots", "render_visual_scene", "visual_digest",
    "CompressionTree", "CostComparisonRow", "EditResonanceProfile", "PolynomialFactorHit", "compare_cost_strategies", "compression_algebra_checklist", "divide_by_linear_root", "edit_distance", "edit_resonance_profile", "hierarchical_compression_tree", "polynomial_factor_search",
    "MatrixTransformer", "VectorMode", "determinant_2x2", "determinant_product_card", "dot_row", "eigen_candidate_card", "linear_algebra_seed_checklist", "matrix_from_ints", "matrix_multiply", "matrix_vector_apply", "trace_2x2", "vector_from_ints", "zero_vector",
    "IntegralCoherence", "LocalLinearization", "antiderivative_polynomial", "calculus_depth_checklist", "chain_rule_card", "compose_polynomials", "integral_coherence", "integral_coherence_card", "linearization_error", "local_linearization", "polynomial_power", "product_rule_card", "scale_polynomial",
    "VeyraCoverageCell", "VeyraCoverageReport", "coverage_language_checklist", "language_coverage_matrix", "language_coverage_report", "missed_language_coverage_rules",
    "VeyraGeneratedMutationReport", "VeyraMutationCase", "VeyraMutationReport", "VeyraMutationResult", "VeyraPropertyFuzzReport", "generated_language_mutation_cases", "generated_language_mutation_report", "generated_mutation_language_checklist", "language_mutation_cases", "language_mutation_report", "mutation_language_checklist", "property_fuzz_language_checklist", "property_language_fuzz_report", "property_language_mutation_cases", "run_generated_language_mutations", "run_language_mutation_case", "run_language_mutations", "run_property_language_fuzz", "shrink_language_mutation_case",
    "Breath", "NativeEcho", "NativeObstruction", "NativeObserver", "NativeShadowRow", "Nod", "Rez", "Tact", "echo_native", "mode", "native_observers", "native_runtime_checklist", "native_runtime_report", "native_shadow_rows", "nod", "observe_native", "rez", "shadow_from_native", "stitch", "tact", "breath",
    "CycleDivisibilityRow", "CycleEcho", "PrimeObstructionRow", "PrimitiveCountRow", "PrimitivePhaseProfile", "RankFactorRow", "SpectrumCompressionRow", "compare_spectrum_compression", "cycle_divisibility_row", "cycle_echo", "cycle_equivalent", "cyclic_weave_echo", "native_number_checklist", "native_number_theory_checklist", "primitive_count_table", "primitive_phase_profile", "prime_obstruction_rows", "rank_factor_comparison",
    "VeyraProofStep", "VeyraProofSummary", "VeyraProofTrace", "proof_language_checklist", "proof_summary", "trace_veyra_proof",
    "PrimitiveModelNote", "RuleCoverageCell", "SemanticDomainRow", "StableExportRow", "primitive_model_notes", "proof_discipline_checklist", "proof_discipline_summary", "proof_rule_coverage", "proof_rule_coverage_summary", "semantic_domain_coverage", "stable_formal_export_rows",
    "DistributionFamily", "IntervalEstimate", "bernoulli_family", "hypothesis_mean_card", "interval_contains_shadow", "mean_interval", "sample_echo_from_ints", "standard_error_shadow", "statistics_inference_checklist",
    "BernoulliLikelihoodRow", "ConcentrationBound", "DecisionErrorRow", "bernoulli_likelihood_row", "chebyshev_mean_bound", "concentration_bound_card", "decision_error_row", "hoeffding_exponent_guard", "likelihood_ratio_card", "statistics_concentration_checklist",
    "DomainResidualCertificate", "LikelihoodPeakCard", "LikelihoodPoint", "LikelihoodSegment", "domain_residual_certificate", "finite_likelihood_segments", "likelihood_geometry_checklist", "likelihood_geometry_summary", "likelihood_grid", "likelihood_peak_card", "likelihood_point", "residual_family_certificates",
    "VeyraSurpriseWitness", "BaselineAuditRow", "ClassicalBlindSignature", "ExpandedClassicalSignature", "DeBruijnBaselineSignature", "DeBruijnTrailRow", "HiddenCorrelationRow", "KWiseBaselineSignature", "KWiseHiddenCorrelationRow", "PairwiseBaselineSignature", "SurpriseSearchRow", "SurpriseSeparationRow", "WordSurpriseScore", "best_surprise_for_mode", "bit_words", "cyclic_window_count_signature", "cyclic_windows", "canonical_surprise_separation_row", "classical_baseline_signature", "expanded_baseline_audit_rows", "debruijn_baseline_signature", "debruijn_hidden_checklist", "debruijn_hidden_summary", "debruijn_trail_adjacencies", "debruijn_trail_hidden_row", "expanded_baseline_search_row", "expanded_classical_signature", "find_surprise_witnesses", "global_parity_counts", "hidden_correlation_rows", "kwise_baseline_signature", "kwise_hidden_correlation_checklist", "kwise_hidden_correlation_summary", "kwise_parity_hidden_correlation_row", "pairwise_baseline_signature", "surface_exact_saving", "surprise_checklist", "surprise_search_checklist", "surprise_search_summary", "surprise_separation_checklist", "surprise_separation_rows", "surprise_separation_summary", "xor_hidden_correlation_row",
    "ParseDiagnostic", "SourceSpan", "SpannedExpr", "SpannedParseResult", "VeyraToken", "diagnostic_excerpt", "lex_veyra", "parse_veyra_spanned", "span_language_checklist", "span_to_plain", "spanned_normal_text",
    "SchoolTranslation", "VeyraCheck", "VeyraExpr", "VeyraInterpretation", "VeyraKind", "core_language_checklist", "expr_kind", "infer_veyra", "interpret_veyra", "normal_text", "normalize_veyra", "parse_veyra", "school_translation_table",
    "BestLowerApproximation", "ReductionAudit", "best_lower_approximation", "descent_reduces_to_best_lower", "z4_reduction_audit", "FiniteDAG", "FiniteSeparationTheoremCard", "ObserverClassDefinition", "TopologicalOrderSeparationRow", "base_witness_graphs", "finite_topological_separation_theorem", "observer_class_definitions", "observer_gap_topology_summary", "topological_baseline_signature", "topological_order_count", "topological_order_separation_family", "UnitarityWitness", "adjoint", "apply_unitary", "born_distribution", "born_total", "conjugate", "inner_product", "is_normalized", "tensor_gates", "tensor_modes", "unitarity_witness", "CrestBraid", "CrestTact", "FiniteObserver", "FiniteObserverDoctrine", "FiniteTransition", "ObserverDescent", "ResidualChainBalance", "CREST_BRAID_SCHEMA", "OBSERVER_BALANCE_SCHEMA", "OBSERVER_DESCENT_SCHEMA", "OBSERVER_DOCTRINE_SCHEMA", "Z4", "compose_transitions", "crest_braid", "distinction_set", "minimal_distinguishers", "observer_by_name", "observer_descent", "observer_response_map", "pullback_observer", "pullback_pairs", "residual_chain_balance", "response_trace", "snapshot_doctrine", "snapshot_observer", "snapshot_transition", "transition_map", "validate_doctrine", "z4_closed_crest_braid", "z4_doctrine", "z4_parity_descent", "z4_shift", "z4_successor", "z4_threshold_descent", "z4_two_tact_balance", "MagicAuditRow", "VEYRA_MAGIC_THESIS", "magic_audit_checklist", "magic_audit_rows", "magic_audit_summary", "AreaCertificate", "BalanceMode", "CompletionInterval", "CongruenceCertificate", "ContinuityCertificate", "CurriculumEdge", "CurriculumGap", "CurriculumNode", "CurriculumSummary", "CyclicPhase", "DriftQuotient", "EventPoint", "FiniteDistribution", "IntersectionCard", "LiftResult", "LimitCertificate", "LinearEquation", "LinearForm", "Mode", "ModeTransformer", "PlaneRelabel", "Polynomial", "PolynomialIdentityEvidence",
    "RatioInterval", "RatioMode", "RegistryCheck", "RegistrySummary", "SageExportRow", "SampleEcho", "ShellCertificate", "TheoremCard", "TheoremSpec", "TriangleSignature", "TremorCorridor", "WeightedOutcome", "algebra_analysis_theorem_specs", "all_theorem_specs", "apply_transformer", "area_additivity_card", "balance_from_int", "binomial_symmetry_card", "check_card", "chord_symmetry_card", "choose_echo", "circle_shell", "compare_balances", "continuity_card", "curriculum_sage_export_rows", "cyclic_chord_echo",
    "compare_ratios", "compose_relabels", "compose_transformers", "corridor_congruence", "corridor_contains", "corridor_interpolate", "corridor_midpoint", "curriculum_edges", "curriculum_summary", "dependency_edges", "depth_pack_theorem_specs", "difference_quotient", "discrete_log_shadow", "drift_stability_card", "expectation", "factorial_echo", "geometry_theorem_specs", "identity_relabel", "independence_card", "line_shell_intersections", "linear_equation_card", "mean_balance_card", "missing_curriculum_concepts", "natural_mode", "natural_shadow", "nth_root_shadow", "parallel_corridors_2d", "phase_period_card", "polynomial_evaluation_card", "polynomial_identity_card", "probability_complement_card", "probability_of", "probability_union_card", "pythagorean_card", "quarter_turn_relabel", "ratio_from_ints",
    "SchoolTopicCoverage", "ratio_power", "relabel_event", "registry_summary", "riemann_area", "sage_export_rows", "sample_mean", "sample_variance", "sampled_continuity", "sas_card", "scale_relabel", "school_curriculum_nodes", "school_topic_coverage_rows", "school_topic_gap_rows", "solve_linear", "squared_separation", "square_refinement", "sss_card", "symmetric_difference_quotient", "tail_limit_certificate", "theorem_sage_export_rows", "translation_relabel", "triangle_area", "triangle_congruence", "turn_2d", "variance_shift_card", "weave_by_length",
]
__all__ += _status_promotion_public.__all__
__all__ += _scoped_formation_public.__all__
__all__ += _observer_actualization_public.__all__
__all__ += _generated_confluence_public.__all__
__all__ += _padic_completion_public.__all__
__all__ += _padic_family_introduction_public.__all__
__all__ += _observer_network_public.__all__
__all__ += _prime_power_productive_bridge_public.__all__
__all__ += _prime_power_reduction_network_public.__all__
__all__ += _padic_local_realization_public.__all__
__all__ += _transport_coherence_public.__all__
