"""Break locus (TR-2/1): where a word loses primitivity across the lattice.

By the TR-1 spine (`THM_TR1_002`/`THM_TR1_003`) the set of doctrines at
which a word is imprimitive is upward closed, so it is generated by an
antichain of minimal breaking doctrines — the **break locus** `B(w)`. This
lane computes `B(w)` through the Δ-characterization: a same-multiset power
candidate `v = u^k` breaks `w` at doctrine `D` exactly when every letter
pair whose pairwise projections differ between `w` and `v` is declared
independent by `D`; hence `B(w)` is the ⊆-minimal antichain of the Δ-sets
over all candidates. The classical projection lemma behind the ⇐ direction
(Cori–Perrin; trace monoids) is credited and **not assumed**: every
certified row cross-checks the Δ-prediction against the BFS trace-class
truth over the full Boolean doctrine lattice, refusals reported, mismatches
fatal. Degenerate poles are classified: a literal power has `B = {∅}`
(breaks already at the word node); a word with no valid exponent is
**absolutely primitive** (`B = ∅`, primitive at every doctrine). Sweep
outcomes are pinned only after exhaustive computation. Enumeration and
counters are docs/06 §3 shadow bookkeeping; break decisions run on
projections and echo objects. Statuses are `witnessed`/`blocked`/`refused`,
never `proved`. See docs/183_break_locus_tr2.md.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations, permutations
import logging

from .observer_lattice import (
    CommutationDoctrine,
    doctrine,
    primitivity_row,
)

logger = logging.getLogger(__name__)

DEFAULT_SWEEP_CAP = 20000
DEFAULT_CLASS_CAP = 1500

Pair = tuple[str, str]


@dataclass(frozen=True)
class PowerCandidateRow:
    """One same-multiset power candidate with its projection delta."""

    power_word: str
    root_word: str
    exponent: int
    delta: tuple[Pair, ...]


@dataclass(frozen=True)
class BreakLocus:
    """The minimal antichain of breaking pair-sets for one word."""

    word: str
    alphabet: tuple[str, ...]
    candidates: tuple[PowerCandidateRow, ...]
    minimal_deltas: tuple[tuple[Pair, ...], ...]
    principal: bool
    literal_power: bool
    absolutely_primitive: bool
    status: str
    obstruction: str


@dataclass(frozen=True)
class CrossCheckReport:
    """Δ-prediction vs BFS truth over the full Boolean doctrine lattice."""

    word: str
    doctrines_checked: int
    refused_doctrines: int
    mismatches: tuple[str, ...]
    status: str
    obstruction: str


@dataclass(frozen=True)
class SweepReport:
    """Exhaustive locus sweep over one multiset shape."""

    shape_id: str
    words_scanned: int
    literal_powers: int
    absolutely_primitive: int
    principal: int
    nonprincipal_words: tuple[str, ...]
    max_locus_size: int
    status: str
    obstruction: str


def pair_projection(word: tuple[str, ...], left: str, right: str) -> tuple[str, ...]:
    """Return the subsequence of the two letters (the pairwise projection)."""
    logger.debug("locus.pair_projection entry %s/%s", left, right)
    result = tuple(letter for letter in word if letter == left or letter == right)
    logger.debug("locus.pair_projection exit length=%d", len(result))
    return result


def delta_pairs(word: tuple[str, ...], other: tuple[str, ...], alphabet: tuple[str, ...]) -> tuple[Pair, ...] | None:
    """Return the pairs whose projections differ, or None on multiset mismatch."""
    logger.debug("locus.delta_pairs entry")
    if sorted(word) != sorted(other):
        logger.debug("locus.delta_pairs exit multiset-mismatch")
        return None
    result = tuple(
        (left, right)
        for left, right in combinations(sorted(alphabet), 2)
        if pair_projection(word, left, right) != pair_projection(other, left, right)
    )
    logger.debug("locus.delta_pairs exit count=%d", len(result))
    return result


def _valid_exponents(counts: tuple[int, ...]) -> tuple[int, ...]:
    logger.debug("locus._valid_exponents entry counts=%r", counts)
    total = sum(counts)
    result = tuple(
        k for k in range(2, total + 1)
        if all(count % k == 0 for count in counts)
    )
    logger.debug("locus._valid_exponents exit result=%r", result)
    return result


def power_candidates(word: tuple[str, ...], alphabet: tuple[str, ...]) -> tuple[PowerCandidateRow, ...]:
    """Enumerate all same-multiset powers v = u^k with their delta sets."""
    logger.debug("locus.power_candidates entry word=%s", "".join(word))
    letters = tuple(sorted(alphabet))
    counts = tuple(word.count(letter) for letter in letters)
    rows: list[PowerCandidateRow] = []
    seen_powers: set[tuple[str, ...]] = set()
    for exponent in _valid_exponents(counts):
        reduced: list[str] = []
        for letter, count in zip(letters, counts):
            reduced.extend([letter] * (count // exponent))
        for root in set(permutations(reduced)):
            power = root * exponent
            if power in seen_powers:
                continue
            seen_powers.add(power)
            delta = delta_pairs(word, power, letters)
            if delta is None:
                logger.error("locus.power_candidates impossible multiset drift")
                continue
            rows.append(PowerCandidateRow("".join(power), "".join(root), exponent, delta))
    result = tuple(sorted(rows, key=lambda row: (len(row.delta), row.power_word)))
    logger.debug("locus.power_candidates exit count=%d", len(result))
    return result


def _minimal_antichain(deltas: tuple[tuple[Pair, ...], ...]) -> tuple[tuple[Pair, ...], ...]:
    logger.debug("locus._minimal_antichain entry count=%d", len(deltas))
    unique = sorted(set(deltas), key=lambda item: (len(item), item))
    minimal: list[tuple[Pair, ...]] = []
    for candidate in unique:
        candidate_set = set(candidate)
        if not any(set(kept) <= candidate_set for kept in minimal):
            minimal.append(candidate)
    result = tuple(minimal)
    logger.debug("locus._minimal_antichain exit count=%d", len(result))
    return result


def break_locus(word: tuple[str, ...], alphabet: tuple[str, ...]) -> BreakLocus:
    """Compute the break locus of a word over the given alphabet."""
    logger.debug("locus.break_locus entry word=%s", "".join(word))
    text = "".join(word)
    letters = tuple(sorted(alphabet))
    if not word or any(letter not in letters for letter in word):
        result = BreakLocus(text, letters, (), (), True, False, False, "blocked", "foreign-or-empty-word")
        logger.error("locus.break_locus blocked foreign-or-empty")
        return result
    candidates = power_candidates(word, letters)
    if not candidates:
        result = BreakLocus(text, letters, (), (), True, False, True, "witnessed", "none")
        logger.debug("locus.break_locus exit absolutely-primitive")
        return result
    minimal = _minimal_antichain(tuple(row.delta for row in candidates))
    literal = minimal == ((),)
    result = BreakLocus(
        text, letters, candidates, minimal,
        len(minimal) <= 1, literal, False, "witnessed", "none",
    )
    logger.debug(
        "locus.break_locus exit minimal=%d principal=%s literal=%s",
        len(minimal), result.principal, literal,
    )
    return result


def predicted_break(locus: BreakLocus, node: CommutationDoctrine) -> tuple[bool, str]:
    """Return the Δ-prediction for one doctrine with its witnessing power."""
    logger.debug("locus.predicted_break entry node=%s", node.doctrine_id)
    independent = set(node.independent_pairs)
    for row in locus.candidates:
        if set(row.delta) <= independent:
            logger.debug("locus.predicted_break exit break witness=%s", row.power_word)
            return (True, row.power_word)
    logger.debug("locus.predicted_break exit no-break")
    return (False, "")


def cross_check_full_lattice(word: tuple[str, ...], alphabet: tuple[str, ...], cap: int = DEFAULT_CLASS_CAP) -> CrossCheckReport:
    """Verify Δ-predictions against BFS truth on every doctrine of the lattice."""
    logger.debug("locus.cross_check_full_lattice entry word=%s", "".join(word))
    text = "".join(word)
    letters = tuple(sorted(alphabet))
    locus = break_locus(word, letters)
    if locus.status != "witnessed":
        result = CrossCheckReport(text, 0, 0, (), "blocked", locus.obstruction)
        logger.error("locus.cross_check blocked %s", locus.obstruction)
        return result
    all_pairs = tuple(combinations(letters, 2))
    checked = refused = 0
    mismatches: list[str] = []
    for size in range(len(all_pairs) + 1):
        for chosen in combinations(all_pairs, size):
            node = doctrine("x".join("".join(pair) for pair in chosen) or "word", letters, chosen)
            if not isinstance(node, CommutationDoctrine):
                mismatches.append("doctrine-build:%r" % (chosen,))
                continue
            prediction, _witness = predicted_break(locus, node)
            row = primitivity_row(node, word, cap)
            if row.status == "refused":
                refused += 1
                continue
            checked += 1
            truth = not row.primitive
            if truth != prediction:
                mismatches.append("%s:predicted=%s:bfs=%s" % (node.doctrine_id, prediction, truth))
    status = "witnessed" if not mismatches else "blocked"
    result = CrossCheckReport(
        text, checked, refused, tuple(mismatches), status,
        "none" if not mismatches else "delta-bfs-mismatch",
    )
    if mismatches:
        logger.error("locus.cross_check mismatches=%d", len(mismatches))
    logger.debug("locus.cross_check exit checked=%d refused=%d", checked, refused)
    return result


def nonprincipal_sweep(alphabet: tuple[str, ...], counts: tuple[int, ...], word_cap: int = DEFAULT_SWEEP_CAP) -> SweepReport:
    """Exhaustively scan one multiset shape for non-principal break loci."""
    logger.debug("locus.nonprincipal_sweep entry alphabet=%r counts=%r", alphabet, counts)
    letters = tuple(sorted(alphabet))
    shape_id = "-".join("%s%d" % (letter, count) for letter, count in zip(letters, counts))
    if len(letters) != len(counts) or any(count < 1 for count in counts):
        result = SweepReport(shape_id, 0, 0, 0, 0, (), 0, "blocked", "invalid-shape")
        logger.error("locus.nonprincipal_sweep blocked invalid-shape")
        return result
    pool: list[str] = []
    for letter, count in zip(letters, counts):
        pool.extend([letter] * count)
    words = set(permutations(pool))
    if len(words) > word_cap:
        result = SweepReport(shape_id, 0, 0, 0, 0, (), 0, "refused", "sweep-size-refusal")
        logger.error("locus.nonprincipal_sweep refused size=%d", len(words))
        return result
    literal = absolute = principal_count = 0
    nonprincipal: list[str] = []
    max_size = 0
    for word in sorted(words):
        locus = break_locus(word, letters)
        if locus.status != "witnessed":
            result = SweepReport(shape_id, 0, 0, 0, 0, (), 0, "blocked", locus.obstruction)
            logger.error("locus.nonprincipal_sweep blocked %s", locus.obstruction)
            return result
        size = len(locus.minimal_deltas)
        max_size = size if size > max_size else max_size
        if locus.literal_power:
            literal += 1
        elif locus.absolutely_primitive:
            absolute += 1
        elif locus.principal:
            principal_count += 1
        else:
            nonprincipal.append(locus.word)
    result = SweepReport(
        shape_id, len(words), literal, absolute, principal_count,
        tuple(nonprincipal), max_size, "witnessed", "none",
    )
    logger.debug(
        "locus.nonprincipal_sweep exit scanned=%d nonprincipal=%d max=%d",
        len(words), len(nonprincipal), max_size,
    )
    return result


@dataclass(frozen=True)
class ForcingReport:
    """Lemma-A/B executable structure for one word."""

    word: str
    prime_exponents: tuple[int, ...]
    forced_by_prime: tuple[tuple[int, tuple[Pair, ...]], ...]
    lemma_a_respected: bool
    single_prime: bool
    forced_locus_law: bool | None
    status: str
    obstruction: str


@dataclass(frozen=True)
class LawSweepReport:
    """Forced-locus-law check over one exhaustive shape."""

    shape_id: str
    words_checked: int
    lemma_a_violations: tuple[str, ...]
    law_mismatches: tuple[str, ...]
    status: str
    obstruction: str


@dataclass(frozen=True)
class TwoPrimeProbeReport:
    """Seeded deterministic sample of a two-prime shape."""

    shape_id: str
    seed: int
    samples: int
    literal_powers: int
    principal: int
    nonprincipal_words: tuple[str, ...]
    max_locus_size: int
    forced_floor_respected: bool
    status: str
    obstruction: str


def is_k_power(sequence: tuple[str, ...], exponent: int) -> bool:
    """Return whether a sequence is a literal k-th power."""
    logger.debug("locus.is_k_power entry k=%d", exponent)
    length = len(sequence)
    if exponent < 2 or length == 0 or length % exponent:
        logger.debug("locus.is_k_power exit False shape")
        return False
    root = sequence[: length // exponent]
    result = root * exponent == sequence
    logger.debug("locus.is_k_power exit result=%s", result)
    return result


def forced_pairs(word: tuple[str, ...], alphabet: tuple[str, ...], exponent: int) -> tuple[Pair, ...]:
    """Return F_k(w): pairs whose projection is not a k-th power (Lemma A floor)."""
    logger.debug("locus.forced_pairs entry k=%d", exponent)
    letters = tuple(sorted(alphabet))
    result = tuple(
        (left, right)
        for left, right in combinations(letters, 2)
        if not is_k_power(pair_projection(word, left, right), exponent)
    )
    logger.debug("locus.forced_pairs exit count=%d", len(result))
    return result


def prime_valid_exponents(word: tuple[str, ...], alphabet: tuple[str, ...]) -> tuple[int, ...]:
    """Return the prime exponents dividing every letter multiplicity."""
    logger.debug("locus.prime_valid_exponents entry")
    from .primes import is_prime_int

    letters = tuple(sorted(alphabet))
    counts = tuple(word.count(letter) for letter in letters)
    result = tuple(k for k in _valid_exponents(counts) if is_prime_int(k))
    logger.debug("locus.prime_valid_exponents exit result=%r", result)
    return result


def forcing_report(word: tuple[str, ...], alphabet: tuple[str, ...]) -> ForcingReport:
    """Counterpressure Lemma A on every candidate and test the forced-locus law."""
    logger.debug("locus.forcing_report entry word=%s", "".join(word))
    text = "".join(word)
    letters = tuple(sorted(alphabet))
    locus = break_locus(word, letters)
    if locus.status != "witnessed":
        result = ForcingReport(text, (), (), False, False, None, "blocked", locus.obstruction)
        logger.error("locus.forcing_report blocked %s", locus.obstruction)
        return result
    primes = prime_valid_exponents(word, letters)
    forced = tuple((q, forced_pairs(word, letters, q)) for q in primes)
    floors = {q: set(pairs) for q, pairs in forced}
    lemma_a = all(
        floors.get(_smallest_prime_factor(row.exponent), set()) <= set(row.delta)
        for row in locus.candidates
    )
    single = len(primes) == 1
    law: bool | None = None
    if single and not locus.literal_power and not locus.absolutely_primitive:
        law = locus.minimal_deltas == (forced[0][1],)
    result = ForcingReport(
        text, primes, forced, lemma_a, single, law,
        "witnessed" if lemma_a else "blocked",
        "none" if lemma_a else "lemma-a-violated",
    )
    if not lemma_a:
        logger.error("locus.forcing_report LEMMA-A VIOLATION word=%s", text)
    logger.debug("locus.forcing_report exit single=%s law=%r", single, law)
    return result


def _smallest_prime_factor(value: int) -> int:
    logger.debug("locus._smallest_prime_factor entry value=%d", value)
    factor = 2
    while factor * factor <= value:
        if value % factor == 0:
            logger.debug("locus._smallest_prime_factor exit result=%d", factor)
            return factor
        factor += 1
    logger.debug("locus._smallest_prime_factor exit result=%d", value)
    return value


def forced_law_sweep(alphabet: tuple[str, ...], counts: tuple[int, ...], word_cap: int = DEFAULT_SWEEP_CAP) -> LawSweepReport:
    """Check Lemma A and the forced-locus law over one exhaustive shape."""
    logger.debug("locus.forced_law_sweep entry counts=%r", counts)
    letters = tuple(sorted(alphabet))
    shape_id = "-".join("%s%d" % (letter, count) for letter, count in zip(letters, counts))
    pool: list[str] = []
    for letter, count in zip(letters, counts):
        pool.extend([letter] * count)
    words = set(permutations(pool))
    if len(letters) != len(counts) or len(words) > word_cap:
        result = LawSweepReport(shape_id, 0, (), (), "refused", "sweep-size-refusal")
        logger.error("locus.forced_law_sweep refused")
        return result
    violations: list[str] = []
    mismatches: list[str] = []
    checked = 0
    for word in sorted(words):
        report = forcing_report(word, letters)
        if report.status == "blocked" and report.obstruction == "lemma-a-violated":
            violations.append(report.word)
            continue
        if report.status != "witnessed":
            result = LawSweepReport(shape_id, checked, tuple(violations), tuple(mismatches), "blocked", report.obstruction)
            logger.error("locus.forced_law_sweep blocked %s", report.obstruction)
            return result
        checked += 1
        if report.forced_locus_law is False:
            mismatches.append(report.word)
    status = "witnessed" if not violations and not mismatches else "blocked"
    result = LawSweepReport(
        shape_id, checked, tuple(violations), tuple(mismatches), status,
        "none" if status == "witnessed" else "forcing-structure-failure",
    )
    logger.debug("locus.forced_law_sweep exit checked=%d", checked)
    return result


def two_prime_probe(alphabet: tuple[str, ...], counts: tuple[int, ...], samples: int, seed: int = 20260827) -> TwoPrimeProbeReport:
    """Deterministically sample a two-prime shape for non-principal loci."""
    logger.debug("locus.two_prime_probe entry counts=%r samples=%d", counts, samples)
    from random import Random

    letters = tuple(sorted(alphabet))
    shape_id = "-".join("%s%d" % (letter, count) for letter, count in zip(letters, counts))
    pool: list[str] = []
    for letter, count in zip(letters, counts):
        pool.extend([letter] * count)
    rng = Random(seed)
    seen: set[tuple[str, ...]] = set()
    attempts = 0
    while len(seen) < samples and attempts < samples * 50:
        attempts += 1
        candidate = pool[:]
        rng.shuffle(candidate)
        seen.add(tuple(candidate))
    if len(seen) < samples:
        result = TwoPrimeProbeReport(shape_id, seed, 0, 0, 0, (), 0, False, "refused", "sampling-exhausted")
        logger.error("locus.two_prime_probe sampling exhausted")
        return result
    literal = principal_count = 0
    nonprincipal: list[str] = []
    max_size = 0
    floor_ok = True
    for word in sorted(seen):
        locus = break_locus(word, letters)
        if locus.status != "witnessed":
            result = TwoPrimeProbeReport(shape_id, seed, 0, 0, 0, (), 0, False, "blocked", locus.obstruction)
            logger.error("locus.two_prime_probe blocked %s", locus.obstruction)
            return result
        report = forcing_report(word, letters)
        floor_ok = floor_ok and report.lemma_a_respected
        size = len(locus.minimal_deltas)
        max_size = size if size > max_size else max_size
        if locus.literal_power:
            literal += 1
        elif locus.principal:
            principal_count += 1
        else:
            nonprincipal.append(locus.word)
    result = TwoPrimeProbeReport(
        shape_id, seed, len(seen), literal, principal_count,
        tuple(nonprincipal[:8]), max_size, floor_ok, "witnessed", "none",
    )
    logger.debug(
        "locus.two_prime_probe exit samples=%d nonprincipal=%d max=%d",
        len(seen), len(nonprincipal), max_size,
    )
    return result


@dataclass(frozen=True)
class AchievedFloorRow:
    """The firstSlice construction attaining the floor at one exponent."""

    exponent: int
    slice_word: str
    attained: bool
    status: str
    obstruction: str


@dataclass(frozen=True)
class FormulaAgreementReport:
    """Break-Locus Formula vs candidate-enumeration locus over one shape."""

    shape_id: str
    words_checked: int
    formula_mismatches: tuple[str, ...]
    unachieved_floors: tuple[str, ...]
    status: str
    obstruction: str


def first_slice(word: tuple[str, ...], alphabet: tuple[str, ...], exponent: int) -> tuple[str, ...]:
    """Keep, for every letter, its first (count/exponent) occurrences."""
    logger.debug("locus.first_slice entry k=%d", exponent)
    letters = tuple(sorted(alphabet))
    budget = {letter: word.count(letter) // exponent for letter in letters}
    kept: list[str] = []
    for letter in word:
        if budget.get(letter, 0) > 0:
            kept.append(letter)
            budget[letter] -= 1
    result = tuple(kept)
    logger.debug("locus.first_slice exit length=%d", len(result))
    return result


def achieved_floor_check(word: tuple[str, ...], alphabet: tuple[str, ...], exponent: int) -> AchievedFloorRow:
    """Verify executably that firstSlice^k attains the floor F_k exactly."""
    logger.debug("locus.achieved_floor_check entry k=%d", exponent)
    letters = tuple(sorted(alphabet))
    counts = tuple(word.count(letter) for letter in letters)
    if exponent < 2 or any(count % exponent for count in counts):
        result = AchievedFloorRow(exponent, "", False, "blocked", "invalid-exponent")
        logger.error("locus.achieved_floor_check blocked invalid-exponent")
        return result
    root = first_slice(word, letters, exponent)
    power = root * exponent
    delta = delta_pairs(word, power, letters)
    floor = forced_pairs(word, letters, exponent)
    attained = delta is not None and tuple(delta) == floor
    result = AchievedFloorRow(
        exponent, "".join(root), attained,
        "witnessed" if attained else "blocked",
        "none" if attained else "floor-not-attained",
    )
    if not attained:
        logger.error("locus.achieved_floor_check FLOOR NOT ATTAINED word=%s k=%d", "".join(word), exponent)
    logger.debug("locus.achieved_floor_check exit attained=%s", attained)
    return result


def locus_formula(word: tuple[str, ...], alphabet: tuple[str, ...]) -> tuple[tuple[Pair, ...], ...]:
    """Closed-form locus: minimal antichain of the prime floors F_q."""
    logger.debug("locus.locus_formula entry word=%s", "".join(word))
    letters = tuple(sorted(alphabet))
    primes = prime_valid_exponents(word, letters)
    floors = tuple(forced_pairs(word, letters, q) for q in primes)
    result = _minimal_antichain(floors) if floors else ()
    logger.debug("locus.locus_formula exit minimal=%d", len(result))
    return result


def refutation_witness() -> tuple[tuple[str, ...], tuple[str, ...]]:
    """Return the explicit non-principal witness word and its alphabet."""
    logger.debug("locus.refutation_witness entry")
    result = (tuple("aaccabbbaccaaccbbb"), ("a", "b", "c"))
    logger.debug("locus.refutation_witness exit length=%d", len(result[0]))
    return result


def formula_agreement_sweep(alphabet: tuple[str, ...], counts: tuple[int, ...], word_cap: int = DEFAULT_SWEEP_CAP) -> FormulaAgreementReport:
    """Check formula == enumeration locus and floor attainment over a shape."""
    logger.debug("locus.formula_agreement_sweep entry counts=%r", counts)
    letters = tuple(sorted(alphabet))
    shape_id = "-".join("%s%d" % (letter, count) for letter, count in zip(letters, counts))
    pool: list[str] = []
    for letter, count in zip(letters, counts):
        pool.extend([letter] * count)
    words = set(permutations(pool))
    if len(letters) != len(counts) or len(words) > word_cap:
        result = FormulaAgreementReport(shape_id, 0, (), (), "refused", "sweep-size-refusal")
        logger.error("locus.formula_agreement_sweep refused")
        return result
    mismatches: list[str] = []
    unachieved: list[str] = []
    for word in sorted(words):
        locus = break_locus(word, letters)
        if locus.status != "witnessed":
            result = FormulaAgreementReport(shape_id, 0, (), (), "blocked", locus.obstruction)
            logger.error("locus.formula_agreement_sweep blocked %s", locus.obstruction)
            return result
        if locus_formula(word, letters) != locus.minimal_deltas:
            mismatches.append(locus.word)
        for q in prime_valid_exponents(word, letters):
            if not achieved_floor_check(word, letters, q).attained:
                unachieved.append("%s@%d" % (locus.word, q))
    status = "witnessed" if not mismatches and not unachieved else "blocked"
    result = FormulaAgreementReport(
        shape_id, len(words), tuple(mismatches), tuple(unachieved), status,
        "none" if status == "witnessed" else "formula-failure",
    )
    logger.debug("locus.formula_agreement_sweep exit checked=%d", len(words))
    return result


@dataclass(frozen=True)
class TightnessReport:
    """Star-construction witness achieving |B(w)| = number of primes."""

    primes: tuple[int, ...]
    word: str
    length: int
    locus_size: int
    special_pattern_ok: bool
    pairwise_incomparable: bool
    status: str
    obstruction: str


@dataclass(frozen=True)
class TypeSpectrumReport:
    """Realized power/not-power pair-type vectors over one shape."""

    shape_id: str
    prime: int
    words_scanned: int
    realized_vectors: tuple[tuple[bool, ...], ...]
    status: str
    obstruction: str


_HUB = "z"
_STAR_LETTERS = ("a", "b", "c", "d", "e", "f")


def tightness_witness(primes: tuple[int, ...]) -> tuple[tuple[str, ...], tuple[str, ...]] | tuple[str]:
    """Build the star word whose break locus has one minimum per prime."""
    logger.debug("locus.tightness_witness entry primes=%r", primes)
    from .primes import is_prime_int

    if (
        not primes or len(set(primes)) != len(primes)
        or any(not is_prime_int(q) for q in primes)
        or len(primes) > len(_STAR_LETTERS)
    ):
        logger.error("locus.tightness_witness invalid primes")
        return ("invalid-primes",)
    total = 1
    for q in primes:
        total *= q
    letters = _STAR_LETTERS[: len(primes)]
    word: list[str] = []
    for gap in range(total):
        for letter, q in zip(letters, primes):
            block = total // q
            if gap % block == 0:
                word.extend([letter] * block)
        word.append(_HUB)
    alphabet = tuple(sorted(letters + (_HUB,)))
    result = (tuple(word), alphabet)
    logger.debug("locus.tightness_witness exit length=%d", len(result[0]))
    return result


def verify_tightness(primes: tuple[int, ...]) -> TightnessReport:
    """Verify |B(w)| equals the prime count with the star membership pattern."""
    logger.debug("locus.verify_tightness entry primes=%r", primes)
    built = tightness_witness(primes)
    if len(built) == 1:
        result = TightnessReport(primes, "", 0, 0, False, False, "blocked", built[0])
        logger.error("locus.verify_tightness blocked %s", built[0])
        return result
    word, alphabet = built
    minimal = locus_formula(word, alphabet)
    letters = _STAR_LETTERS[: len(primes)]
    floors = {q: set(forced_pairs(word, alphabet, q)) for q in primes}
    pattern_ok = True
    for letter, q in zip(letters, primes):
        special = tuple(sorted((letter, _HUB)))
        pattern_ok = pattern_ok and special not in floors[q]
        for other in primes:
            if other != q:
                pattern_ok = pattern_ok and special in floors[other]
    incomparable = all(
        not (floors[left] <= floors[right])
        for left in primes for right in primes if left != right
    )
    ok = len(minimal) == len(primes) and pattern_ok and incomparable
    result = TightnessReport(
        primes, "".join(word), len(word), len(minimal), pattern_ok, incomparable,
        "witnessed" if ok else "blocked",
        "none" if ok else "tightness-pattern-failure",
    )
    if not ok:
        logger.error("locus.verify_tightness FAILURE primes=%r size=%d", primes, len(minimal))
    logger.debug("locus.verify_tightness exit size=%d", len(minimal))
    return result


def type_matrix(word: tuple[str, ...], alphabet: tuple[str, ...]) -> tuple[tuple[Pair, tuple[tuple[int, bool], ...]], ...]:
    """Return, per pair and prime exponent, whether the projection is a power."""
    logger.debug("locus.type_matrix entry word=%s", "".join(word))
    letters = tuple(sorted(alphabet))
    primes = prime_valid_exponents(word, letters)
    result = tuple(
        (
            (left, right),
            tuple(
                (q, is_k_power(pair_projection(word, left, right), q))
                for q in primes
            ),
        )
        for left, right in combinations(letters, 2)
    )
    logger.debug("locus.type_matrix exit pairs=%d", len(result))
    return result


def type_spectrum_sweep(alphabet: tuple[str, ...], counts: tuple[int, ...], prime: int, word_cap: int = DEFAULT_SWEEP_CAP) -> TypeSpectrumReport:
    """Collect which power/not vectors over pairs are realized in one shape."""
    logger.debug("locus.type_spectrum_sweep entry counts=%r prime=%d", counts, prime)
    letters = tuple(sorted(alphabet))
    shape_id = "-".join("%s%d" % (letter, count) for letter, count in zip(letters, counts))
    pool: list[str] = []
    for letter, count in zip(letters, counts):
        pool.extend([letter] * count)
    words = set(permutations(pool))
    if len(letters) != len(counts) or len(words) > word_cap:
        result = TypeSpectrumReport(shape_id, prime, 0, (), "refused", "sweep-size-refusal")
        logger.error("locus.type_spectrum_sweep refused")
        return result
    realized: set[tuple[bool, ...]] = set()
    for word in sorted(words):
        vector = tuple(
            is_k_power(pair_projection(word, left, right), prime)
            for left, right in combinations(letters, 2)
        )
        realized.add(vector)
    result = TypeSpectrumReport(
        shape_id, prime, len(words), tuple(sorted(realized)), "witnessed", "none"
    )
    logger.debug("locus.type_spectrum_sweep exit realized=%d", len(realized))
    return result


def break_locus_checklist() -> tuple[str, ...]:
    """Return the TR-2/1 lane acceptance checklist."""
    logger.debug("locus.checklist entry")
    result = (
        "the break locus is the minimal antichain of delta sets over all same-multiset power candidates",
        "the classical projection lemma is cross-checked, not assumed: predictions face BFS truth on the full lattice",
        "literal powers have locus {empty}; words with no valid exponent are absolutely primitive with empty locus",
        "sweep outcomes are pinned only after exhaustive computation; oversized sweeps refuse, never truncate",
        "the up-closedness spine is THM_TR1_002/003; a native projection-lemma formalization stays OPEN; nothing here is proved",
    )
    logger.debug("locus.checklist exit count=%d", len(result))
    return result
