"""Sibling structural bridge ledger beside the fixed eight-row F5 ledger."""

from __future__ import annotations

from collections import Counter
import logging

from .comparative_ledger_types import (
    ComparativeBridgeRow,
    ComparativeBridgeStatus,
    ComparativeEvidenceRef,
)
from .certify_observer_patch_atlas import observer_patch_atlas_lean_evidence
from .observer_patch_atlas import triangle_counterexample
from .observer_patch_gluing_classification import (
    classify_exact_gluings,
    disjoint_singleton_nonuniqueness,
)

logger = logging.getLogger(__name__)

COMPARATIVE_BRIDGE_SCHEMA = "veyra.comparative-bridge-ledger.v1"
_EVIDENCE_KINDS = frozenset({"executable", "lean", "counterexample", "document"})


def comparative_bridge_rows() -> tuple[ComparativeBridgeRow, ...]:
    """Return the minimal structural bridge ledger with exact status boundaries."""
    logger.debug("comparative_bridge_rows entry")
    lean = observer_patch_atlas_lean_evidence()
    nonunique = disjoint_singleton_nonuniqueness()
    triangle = triangle_counterexample()
    triangle_class = classify_exact_gluings(triangle.atlas, triangle.sections)
    g4_checked = (
        nonunique.classification.criterion.exact_gluing_exists
        and nonunique.classification.classification_holds
        and nonunique.classification.uniqueness_iff_conflict_complete
        and not triangle_class.criterion.exact_gluing_exists
        and triangle_class.classification_holds
        and lean.digest_status == "matched"
        and lean.lean_status == "checked"
        and lean.symbols_exact
        and lean.helpers_exact
    )
    rows = (
        ComparativeBridgeRow(
            COMPARATIVE_BRIDGE_SCHEMA,
            "CB-ECHO-001",
            "observer-indexed echo relation",
            "indexed families of binary relations",
            ComparativeBridgeStatus.KNOWN_ANALOGUE,
            "relational vocabulary only",
            ("observer ↔ index", "echo predicate ↔ indexed relation"),
            "relation arity and observer indexing",
            "not established beyond the named vocabulary",
            "Veyra doctrine and response semantics are not supplied by the analogue",
            (ComparativeEvidenceRef("DOC-CB-001", "document", "docs/162_comparative_bridge_separation_ledger.md", True),),
            "analogy is not an equivalence, reduction, novelty, or superiority claim",
        ),
        ComparativeBridgeRow(
            COMPARATIVE_BRIDGE_SCHEMA,
            "CB-PROCESS-001",
            "finite observer process semantics",
            "coalgebraic behaviour and bisimulation",
            ComparativeBridgeStatus.OPEN,
            "candidate comparison only",
            (),
            "not established",
            "not established",
            "typing, doctrine, obstruction, and response structure remain unmatched",
            (ComparativeEvidenceRef("DOC-CB-001", "document", "docs/162_comparative_bridge_separation_ledger.md", True),),
            "no functor, equivalence, preservation theorem, or separation theorem is claimed",
        ),
        ComparativeBridgeRow(
            COMPARATIVE_BRIDGE_SCHEMA,
            "CB-G4-001",
            "finite G4 exact observer-patch gluing existence",
            "matching-family amalgamation for the set-valued presheaf V ↦ EqRel(V)",
            ComparativeBridgeStatus.REDUCED if g4_checked else ComparativeBridgeStatus.OPEN,
            "one declared finite cover by named subsets and a pairwise-compatible local family; exact equivalence-relation restrictions",
            (
                "patch ↔ subset of U",
                "local section ↔ equivalence relation on a patch",
                "pairwise overlap row ↔ equality after restriction",
                "E* ↔ least equivalence relation generated by local equalities",
                "exact global gluing ↔ amalgam with exact restrictions",
            ),
            "existence and exact restriction on the declared finite family",
            "the executable correspondence checks both directions of the finite existence criterion",
            "uniqueness is separate; full sheaf data, topology, and general descent are absent",
            (
                ComparativeEvidenceRef("G4-EXEC", "executable", "src/core/observer_patch_atlas.py", g4_checked),
                ComparativeEvidenceRef("G4-CLASS", "executable", "src/core/observer_patch_gluing_classification.py", g4_checked),
                ComparativeEvidenceRef("G4-LEAN", "lean", "proofs/lean/VeyraObserverPatchAtlas.lean", g4_checked),
            ),
            "finite existence/effectivity fragment only; no general sheaf, stack, topology, novelty, or superiority claim",
        ),
    )
    result = tuple(validate_comparative_bridge_row(row) for row in rows)
    logger.debug("comparative_bridge_rows exit count=%d", len(result))
    return result


def validate_comparative_bridge_row(value: object) -> ComparativeBridgeRow:
    """Validate one exact bounded bridge row and its status obligations."""
    logger.debug("validate_comparative_bridge_row entry")
    if type(value) is not ComparativeBridgeRow:
        logger.error("validate_comparative_bridge_row exact type rejected")
        raise ValueError("comparative-bridge-row-must-be-exact")
    strings = (
        value.schema,
        value.bridge_id,
        value.veyra_construct,
        value.comparison_formalism,
        value.scope,
        value.preservation,
        value.reflection,
        value.extra_structure,
        value.boundary,
    )
    valid = (
        value.schema == COMPARATIVE_BRIDGE_SCHEMA
        and all(_bounded_text(item) for item in strings)
        and type(value.status) is ComparativeBridgeStatus
        and type(value.correspondence) is tuple
        and len(value.correspondence) <= 16
        and all(type(item) is str and bool(item) for item in value.correspondence)
        and type(value.evidence) is tuple
        and 1 <= len(value.evidence) <= 8
        and all(_valid_evidence(item) for item in value.evidence)
    )
    if not valid:
        logger.error("validate_comparative_bridge_row shape rejected id=%s", value.bridge_id)
        raise ValueError("invalid-comparative-bridge-row")
    if value.status is ComparativeBridgeStatus.REDUCED and (
        not value.correspondence or not all(item.checked for item in value.evidence)
    ):
        logger.error("validate_comparative_bridge_row unsupported reduction")
        raise ValueError("comparative-bridge-reduced-without-evidence")
    if value.status is ComparativeBridgeStatus.OPEN and value.reflection != "not established":
        logger.error("validate_comparative_bridge_row open row overstates reflection")
        raise ValueError("comparative-bridge-open-overclaim")
    logger.debug("validate_comparative_bridge_row exit id=%s", value.bridge_id)
    return value


def comparative_bridge_summary(rows: tuple[ComparativeBridgeRow, ...] | None = None) -> dict[str, int | bool]:
    """Return status counts and truth-maintenance checks for the bridge ledger."""
    logger.debug("comparative_bridge_summary entry supplied=%s", rows is not None)
    captured = comparative_bridge_rows() if rows is None else tuple(validate_comparative_bridge_row(row) for row in rows)
    counts = Counter(row.status.value for row in captured)
    result: dict[str, int | bool] = {
        "rows": len(captured),
        "known_analogue": counts[ComparativeBridgeStatus.KNOWN_ANALOGUE.value],
        "candidate_bridge": counts[ComparativeBridgeStatus.CANDIDATE_BRIDGE.value],
        "reduced": counts[ComparativeBridgeStatus.REDUCED.value],
        "open": counts[ComparativeBridgeStatus.OPEN.value],
        "unique_ids": len({row.bridge_id for row in captured}) == len(captured),
        "all_checked_reductions": all(row.status is not ComparativeBridgeStatus.REDUCED or all(item.checked for item in row.evidence) for row in captured),
    }
    logger.debug("comparative_bridge_summary exit result=%r", result)
    return result


def comparative_bridge_checklist() -> tuple[str, ...]:
    """Return fixed acceptance rules for bridge status changes."""
    logger.debug("comparative_bridge_checklist entry")
    result = (
        "bridge and separation status spaces stay disjoint",
        "REDUCED requires an exact correspondence and checked evidence",
        "OPEN supplies no preservation or reflection theorem",
        "finite matching-family amalgamation is not a general sheaf claim",
        "no structural row implies novelty or superiority",
    )
    logger.debug("comparative_bridge_checklist exit count=%d", len(result))
    return result


def _valid_evidence(value: object) -> bool:
    """Check one exact bounded in-repository evidence reference."""
    logger.debug("_valid_evidence entry")
    result = (
        type(value) is ComparativeEvidenceRef
        and _bounded_text(value.evidence_id)
        and value.kind in _EVIDENCE_KINDS
        and _bounded_text(value.location)
        and not value.location.startswith("/")
        and type(value.checked) is bool
    )
    logger.debug("_valid_evidence exit result=%s", result)
    return result


def _bounded_text(value: object) -> bool:
    """Return whether one field is nonempty bounded UTF-8 text."""
    logger.debug("_bounded_text entry type=%s", type(value).__name__)
    if type(value) is not str or not value:
        logger.debug("_bounded_text exit result=False")
        return False
    try:
        result = len(value.encode("utf-8")) <= 2_048
    except UnicodeError:
        logger.error("_bounded_text encoding rejected")
        return False
    logger.debug("_bounded_text exit result=%s", result)
    return result
